instance BAU_2009_Martin (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Martin";
Npctype = Npctype_Main;
guild = GIL_BAU;
level = 40;
voice = 5;
id = 2009;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 120;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",0,3,"Hum_Head_Bald", 124,  4, BAU_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Long_02);
EquipItem		(self, ItRw_Bow_Long_09);
CreateInvItems  (self,ItFoApple,15);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItForice,1);
CreateInvItems  (self,Schutzring_Feuer1,1);
CreateInvItems  (self,ItMw_1H_Scythe_01,1);

//----------Handlarz_aivar------
self.aivar[AIV_NPCISTRADER] = true;
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_2009;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2009 ()
{
TA_SitAround (06,00,23,00,"LAWKA_MARTINA");
TA_Sleep (23,00,06,00,"MARTIN_SLEEP");
};
FUNC VOID Rtn_wait_2009 ()
{
TA_Stay (06,00,18,00,"MARTIN");
TA_Stand (18,00,21,20,"MARTIN");
TA_Smoke (21,20,23,00,"MARTIN");
TA_Stand (23,00,06,00,"MARTIN");
};
FUNC VOID Rtn_atak_2009 ()
{
TA_FollowPC (06,00,18,00,"MARTIN");
TA_FollowPC (18,00,21,20,"MARTIN");
TA_FollowPC (21,20,23,00,"MARTIN");
TA_FollowPC (23,00,06,00,"MARTIN");
};
FUNC VOID Rtn_patrol_2009 ()
{
TA_Stand (06,00,18,00,"TRUP");
TA_Stay (18,00,21,20,"TRUP");
TA_Stand (21,20,23,00,"TRUP");
TA_Smoke (23,00,06,00,"TRUP");
};