instance BAU_2012_Rocky (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Rocky";
Npctype = Npctype_Main;
guild = GIL_BAU;
level = 55;
voice = 6;
id = 2012;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");

Mdl_SetVisualBody (self,"hum_body_Naked0",0, 2, "Hum_Head_FatBald", 130, 2, BAU_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
Npc_SetTalentSkill (self, NPC_TALENT_2H,9);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Axe_Old_02);
EquipItem		(self, ItRw_Bow_Long_07);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItForice,1);
CreateInvItems  (self,Schutzring_Feuer1,1);
CreateInvItems  (self,ItMw_1H_Scythe_01,1);
CreateInvItems  (self,ItAt_Wolf_01,1);
CreateInvItems  (self,ItAt_Claws_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2012;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2012 ()
{
TA_Sleep (01,10,07,35,"ROCKY_BED");
TA_skrzynka (07,35,09,00,"CHEST_BAU");
TA_Smith_Sharp (09,00,11,45,"OSELKA1");
TA_RepairHut (11,45,13,15,"ROCKY");
TA_PracticeSword (13,15,15,00,"BN_TRENING_WSZYSCY");
TA_Smoke (15,00,17,20,"LOCATION_11_12_01");
TA_Smith_Sharp (17,20,18,20,"OSELKA1");
TA_Smalltalk (18,20,21,20,"ROCKY");
TA_SitAround (21,20,01,10,"QUENTIN_SIT");
};
FUNC VOID Rtn_atak_2012 ()
{
TA_GuidePC (06,00,12,00,"ATAK009");
TA_GuidePC (12,00,16,40,"ATAK009");
TA_GuidePC (16,40,18,00,"ATAK009");
TA_GuidePC (18,00,06,00,"ATAK009");
};
FUNC VOID Rtn_atak2_2012 ()
{
TA_GuidePC (06,00,12,00,"ESKORTA1");
TA_GuidePC (12,00,16,40,"ESKORTA1");
TA_GuidePC (16,40,18,00,"ESKORTA1");
TA_GuidePC (18,00,06,00,"ESKORTA1");
};
FUNC VOID Rtn_ucieczka_2012 ()
{
TA_Stand (06,00,12,00,"OW_PATH_1_5_A");
TA_Stand (12,00,16,40,"OW_PATH_1_5_A");
TA_Stand (16,40,18,00,"OW_PATH_1_5_A");
TA_Stand (18,00,06,00,"OW_PATH_1_5_A");
};
FUNC VOID Rtn_mine_2012 ()
{
TA_Stand_Ignorance (06,00,12,00,"CAMP01");
TA_Stand_Ignorance (12,00,16,40,"CAMP01");
TA_Stand_Ignorance (16,40,18,00,"CAMP01");
TA_Stand_Ignorance (18,00,06,00,"CAMP01");
};
FUNC VOID Rtn_odb_2012 ()
{
TA_FollowPC (06,00,12,00,"OW_PATH_1_5_A");
TA_FollowPC (12,00,16,40,"OW_PATH_1_5_A");
TA_FollowPC (16,40,18,00,"OW_PATH_1_5_A");
TA_FollowPC (18,00,06,00,"OW_PATH_1_5_A");
};
