instance GRD_2003_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 14;
voice = 7;
id = 2003;

//----------Statystyki----------

attribute[ATR_STRENGTH] 		= 55;
	attribute[ATR_DEXTERITY] 	= 50;
	attribute[ATR_MANA_MAX] 	= 0;
	attribute[ATR_MANA] 		= 0;
	attribute[ATR_HITPOINTS_MAX]= 180;
	attribute[ATR_HITPOINTS] 	= 180;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",114, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
//Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
//EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFocheese,1);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoBeer,1);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2003;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2003 ()
{
TA_PracticeSword (06,00,12,00,"PLAC3");
TA_StandAround (12,00,15,00,"PLAC3");
TA_RepairHut (15,00,18,00,"WP_INTRO_WI07");
TA_SitCampfire (18,00,06,00,"PLAC3");
};
FUNC VOID Rtn_atakn_2003 ()
{
TA_Stand (06,00,12,00,"OW_PATH_1_16_6");
TA_Boss (12,00,15,00,"OW_PATH_1_16_6");

};