instance GRD_5099_Kwatermistrz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Spark";
Npctype = Npctype_main;
guild = GIL_GRD;
level = 20;
voice = 7;
id = 5099;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 190;
attribute[ATR_HITPOINTS] = 190;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",107, 1,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,6);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItAt_Teeth_01,1);
CreateInvItems  (self,ItFoApple,4);
CreateInvItems  (self,itminugget,150);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5099;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5099 ()
{ //ER_PLAC_WHEEL
TA_SitAround (18,33,13,25,"ER_PLAC_KWA1");
TA_Cook (13,25,15,20,"ER_PLAC_KUCH1");
TA_Boss (15,00,18,33,"ER_PLAC_KWA2");
};
