instance GRD_2013_Siepacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Siepacz";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 7;
voice = 8;
id = 2013;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 37;
attribute[ATR_DEXTERITY] = 18;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 110;
attribute[ATR_HITPOINTS] = 110;

	// 			animations
	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex,teethtex,ruestung	
	Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 13,  1, STT_ARMOR_M);
        
	B_Scale (self);
    	Mdl_SetModelFatness(self,2);
    	
    	fight_tactic	=	FAI_HUMAN_STRONG;

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFoBeer,2);
CreateInvItems  (self,ItFo_Plants_Herb_01,3);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
CreateInvItems  (self,ItMiNugget,120);
//----------Pozostale----------
daily_routine = Rtn_start_2013;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2013 ()
{
TA_Smalltalk (06,00,22,00,"SIEP1");
TA_Stand (22,00,06,00,"SIEP1");
};
FUNC VOID Rtn_follow_2013 ()
{
TA_FollowPC (06,00,12,00,"SIEP1");
TA_FollowPC (12,00,06,00,"SIEP1");
};
FUNC VOID Rtn_away_2013 ()
{
TA_Stay (06,00,12,00,"");
TA_Stay (12,00,06,00,"");
};