instance GRD_7008_Tukash (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Andrew";
Npctype	= NPCTYPE_MAIN;
guild = GIL_STT;
level = 20;
voice = 15;
id = 7008;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 259;
attribute[ATR_HITPOINTS] = 259;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 2,"Hum_Head_Bald",2, 2,STT_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

	//----------Handlarz_aivar------
	self.aivar[AIV_NPCISTRADER] = true;
	
//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);//fix

//----------Ekwipunek----------
EquipItem		(self, Miecz1H1);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoBeer,9);
CreateInvItems  (self,ItFoWine,12);
CreateInvItems  (self,ItMiNugget,120);
CreateInvItems  (self,ItAt_Claws_01,8);
CreateInvItems  (self,ItFo_Potion_Health_01,30);
CreateInvItems  (self,ItKeLockpick,50);
CreateInvItems  (self,ItMiHammer,5);
CreateInvItems  (self,ItMiScoop,5);
CreateInvItems  (self,ItLsTorch,33);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7008;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7008 ()
{
TA_Stand (07,25,15,00,"TRADER");
TA_Smoke (15,00,20,00,"TRADER");
TA_PlayTune (20,00,22,35,"TRADER");//fp dodany
TA_Sleep (22,35,07,25,"OMC_BED_ANDREW");
};
FUNC VOID Rtn_ucieczka_7008 ()
{
TA_Stay (06,00,12,00,"HELP2");
TA_Sleep (12,00,18,00,"HELP2");
TA_Stand (18,00,22,00,"HELP2");
TA_Smoke (22,00,06,00,"HELP2");
};
func void rtn_atak_7008 ()
{
TA_GuidePC (06,00,12,00,"OW_PATH_058");
TA_GuidePC (12,00,06,00,"OW_PATH_058");
};
func void rtn_atak2_7008 ()
{
TA_Helper (06,00,12,00,"OW_PATH_056");
TA_helper (12,00,06,00,"OW_PATH_056");
};

func void rtn_follow_7008 ()
{
TA_FollowPC (06,00,12,00,"OW_PATH_056");
TA_FollowPC (12,00,06,00,"OW_PATH_056");
};