instance GRD_7002_KUCHARZ (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Matt";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 12;
voice = 10;
id = 7002;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 45;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 145;
attribute[ATR_HITPOINTS] = 145;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds		(self,"Humans_Militia.mds");
Mdl_SetVisualBody		 (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",121, 0,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
CreateInvItems  (self,ItAt_Wolf_01,1);
CreateInvItems  (self,VLK_ARMOR_M,1);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoMutton,5);
CreateInvItems  (self,ItForice,2);
CreateInvItems  (self,ItFoWine,8);
CreateInvItems  (self,ItFo_Potion_Health_01,10);
CreateInvItems  (self,Schutzring_Feuer1,1);
CreateInvItems  (self,ItKeLockpick,5);
CreateInvItems  (self,ItMiHammer,1);
CreateInvItems  (self,ItMiLute,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7002;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7002 ()
{
TA_Cook (06,00,12,00,"KUCHARZ");
TA_Stay (12,00,14,00,"KUCHARZ3");
TA_Cook (14,00,18,22,"KUCHARZ");
TA_Smoke (18,22,20,00,"KUCHARZ3");
TA_Cook (20,00,23,00,"KUCHARZ");
TA_Sleep (23,00,06,00,"OMC_BED_KUCHARZ");
};
FUNC VOID Rtn_ded_7002 ()
{
TA_Stay (06,00,12,00,"WAR4");
TA_Stay (12,00,06,00,"WAR4");
};