instance GRD_7007_Mirzo (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Mirzo";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 13;
voice = 11;
id = 7007;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 55;
attribute[ATR_DEXTERITY] = 45;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 168;
attribute[ATR_HITPOINTS] = 168;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",25, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,4);
Npc_SetTalentSkill (self, NPC_TALENT_1H,6);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoBeer,9);
CreateInvItems  (self,ItFoWine,12);
CreateInvItems  (self,ItMiNugget,120);
CreateInvItems  (self,ItAt_Claws_01,8);
CreateInvItems  (self,VLK_ARMOR_L,1);
CreateInvItems  (self,VLK_ARMOR_M,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7007;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7007 ()
{
TA_Guard (05,20,00,15,"OMC_OREWAGON_GUARD");
TA_Sleep (00,15,05,20,"OMC_BED_MIRZO");
};
FUNC VOID Rtn_spisek_7007 ()
{
TA_Guard (02,30,00,00,"OMC_OREWAGON_GUARD"); 
TA_Smalltalk (00,10,02,30,"MIRZO_SPISEK"); //with OW_PATH_07_21_GUARD_LEFT
};
FUNC VOID Rtn_spisek2_7007 ()
{
TA_Smalltalk (02,30,00,00,"MIRZO_SPISEK"); 
TA_Smalltalk (00,00,02,30,"MIRZO_SPISEK"); //with OW_PATH_07_21_GUARD_LEFT
};
FUNC VOID Rtn_obrona_7007 ()
{
TA_Stand (06,00,12,00,"WAR5");
TA_Guard (12,00,06,00,"WAR5");
};

FUNC VOID Rtn_paka_7007 ()
{
TA_SitCampfire (06,00,12,00,"MIRZO_PAKA");
TA_SitCampfire (12,00,06,00,"MIRZO_PAKA");
};
