instance GRD_7004_Gamal (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Petro";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 15;
voice = 5;
id = 7004;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 2,"Hum_Head_Bald",0, 2,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Crossbow_01); //eq i skill zmienione g1210
CreateInvItems  (self,ItAt_Meatbug_01,2);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItForice,8);
CreateInvItems  (self,ItMiNugget,60);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7004;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7004 ()
{
TA_SitAround (06,00,18,00,"PATH_OC_NC");
TA_SitAround (18,00,06,00,"PATH_OC_NC");
};
FUNC VOID Rtn_went_7004 ()
{
TA_GuidePC (06,00,22,00,"OW_OM_ENTRANCE01");
TA_GuidePC (22,00,06,00,"OW_OM_ENTRANCE01");
};

FUNC VOID Rtn_camp_7004 ()
{
TA_Guard (06,00,12,00,"GRD2");
TA_Stand (12,00,16,00,"KAR3");
TA_Guard (16,00,21,00,"GRD15");
TA_Stand (21,00,06,00,"KAR3");
};
