instance GRD_2035_Dracon (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Dracon";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 24;
voice = 2;
id = 2035;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 140;
attribute[ATR_HITPOINTS] = 140;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 3,"Hum_Head_Bald",10, 3,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoApple,3);
CreateInvItems  (self,ItFoMuttonRaw,5);
CreateInvItems  (self,ItKeLockpick,5);
CreateInvItems  (self,ItMiScoop,1);
CreateInvItems  (self,ItMiNugget,350);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2035;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2035 ()
{
TA_Guard (06,12,18,00,"PATROL1");
TA_Guard (18,00,06,12,"PATROL1");
};
FUNC VOID Rtn_wlam_2035 ()
{
TA_Smalltalk (06,00,22,00,"PATROL2");
TA_Smalltalk (22,00,06,00,"PATROL2");
};
