instance GRD_2293_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stra¿nik";
Npctype = Npctype_Ambient;
guild = GIL_GRD;
level = 70;
voice = 13;
id = 2293;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 90;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",52, 1,GRD_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Bastard_01);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItMiNugget,30);
CreateInvItems  (self,ItMiSwordraw,2);
CreateInvItems  (self,Ring_des_Lebens,1);
CreateInvItems  (self,ItFo_Potion_Health_01,7);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2293;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2293 ()
{
TA_Guard (06,00,18,00,"OW_PATH_1_15");
TA_Guard (18,00,06,00,"OW_PATH_1_15");
};
