instance GRD_7005_Spike (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Spike";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 20;
voice = 9;
id = 7005;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 45;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 230;
attribute[ATR_HITPOINTS] = 230;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Fighter",110, 1,GRD_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItMiNugget,20);
CreateInvItems  (self,ItFo_Potion_Health_01,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7005;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_7005 ()
{
TA_Guard (05,30,21,44,"GRD4");
TA_Sleep (21,44,05,30,"OMC_BED_SPIKE");
};
FUNC VOID Rtn_ded_7005 ()
{
TA_Guard (06,00,18,35,"WAR2");
TA_SitCampfire (18,35,03,00,"WAR2");
TA_Stand (03,00,06,00,"WAR2");
};