instance GRD_3934_Berg (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Berg";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 3934;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",12, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoMutton,2);
CreateInvItems  (self,ItFoBeer,3);
CreateInvItems  (self,ItFo_Potion_Health_01,3);
CreateInvItems  (self,ItMijoint_1,1);
CreateInvItems  (self,ItLsTorch,1);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_quest_3934;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_quest_3934 ()
{
TA_SitAround (00,00,09,00,"CHUJ1");
TA_Smoke (09,00,15,00,"CHUJ1");
TA_SitAround (15,00,23,00,"CHUJ1");
};
FUNC VOID Rtn_quest_aidan_3934 ()
{
TA_Stand (06,00,18,00,"SLD2");
TA_Stand (18,00,06,00,"SLD2");
};
FUNC VOID Rtn_start_3934 ()
{
TA_SitAround (00,00,07,00,"OCR_HUT_Z5_SIT4");
TA_Stand (07,00,12,00,"BERG_LIFE");
TA_PracticeSword (12,00,14,50,"OCC_CENTER_4_TRAIN3");
TA_Smoke (14,50,17,00,"OCC_WELL_RIGHT_MOVEMENT2");
TA_Stand (17,50,19,00,"BERG_LIFE");
TA_SitAround (19,00,23,00,"OCR_HUT_Z5_SIT4");
};