instance NON_5675_Magnus (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Magnus";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 15;
voice = 11;
id = 5675;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 170;
attribute[ATR_HITPOINTS] = 170;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1,"Hum_Head_Pony", 49, 1,NON_LEATHER_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------

EquipItem		(self, ItMw_1H_Sword_02);
EquipItem		(self, ItRw_Bow_Long_03);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItMiNugget,25);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5675;
};

FUNC VOID Rtn_start_5675 ()
{
TA_SitCampfire (06,00,14,33,"MANGUS");
TA_Stand (14,33,15,21,"MANGUS");
TA_PlayTune (15,21,06,00,"MANGUS");//fp dodany
};

FUNC VOID Rtn_karczma_5675 ()
{
TA_Smoke (06,00,14,33,"MANGUS2");
TA_Stand (14,33,15,21,"MANGUS2");
TA_Smoke (15,21,06,00,"MANGUS2");
};

FUNC VOID Rtn_follow_5675 ()
{
TA_FollowPC (06,00,14,33,"OW_PATH_067");
TA_FollowPC (14,33,15,21,"OW_PATH_067");
TA_FollowPC (15,21,06,00,"OW_PATH_067");
};

FUNC VOID Rtn_mine_5675 ()
{
TA_Boss (06,00,14,33,"OW_PATH_07_15_CAVE2");
TA_Boss (14,33,15,21,"OW_PATH_07_15_CAVE2");
TA_Boss (15,21,06,00,"OW_PATH_07_15_CAVE2");
};

FUNC VOID Rtn_flee_5675 ()
{
TA_Stay (00,00,12,00,"");
TA_Stay (12,00,00,00,"");
};

instance NON_5676_MagnusOT (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Magnus";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 100;  //¿eby nie ucieka³ przed przeciwnikami
voice = 11;
id = 5676;
flags = 2;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 350;
attribute[ATR_HITPOINTS] = 350;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1,"Hum_Head_Pony", 49, 1,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,8);

//----------Ekwipunek----------

EquipItem		(self, ItMw_1H_Sword_Long_05);
EquipItem		(self, ItRw_Bow_Long_03);
EquipItem		(self, Helmet2);
CreateInvItems  (self,ItFoApple,5);


//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_startOT_5676;
};

FUNC VOID Rtn_startOT_5676 ()
{
TA_Stay (00,00,12,00,"TPL_319");
TA_Stay (12,00,00,00,"TPL_319");
};

FUNC VOID Rtn_follow_5676 ()
{
TA_FollowPC (00,00,12,00,"TPL_319");
TA_FollowPC (12,00,00,00,"TPL_319");
};

FUNC VOID Rtn_die_5676 ()
{
TA_Die (00,00,12,00,"TPL_319");
TA_Die (12,00,00,00,"TPL_319");
};