instance NON_3089_Ashton (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Ashton";
Npctype = Npctype_Main;
guild = GIL_SLD;
level = 60;
voice = 15;
id = 3089;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 130;
attribute[ATR_DEXTERITY] = 300;
attribute[ATR_MANA_MAX] = 70;
attribute[ATR_MANA] = 70;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",8, 1,SLD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,1);
Npc_SetTalentSkill (self, NPC_TALENT_MAGE,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_05);
EquipItem		(self, ItRw_Crossbow_04);
CreateInvItems  (self,ItMijoint_1,1);
CreateInvItems  (self,ItMiNugget,350);
CreateInvItems  (self,ItFo_Potion_Health_01,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_3089;
//Generated by Gothic NPC Maker
};
func void Rtn_start_3089 ()
{
TA_Stay (06,00,00,00,"CASTLE_6");
TA_Smalltalk (00,00,04,00,"LOWCAX3");
TA_Stand (04,00,06,00,"CASTLE_6");
};
func void Rtn_bicz_3089 ()
{
TA_GuidePC (06,00,00,00,"CULT1");
TA_GuidePC (00,00,04,00,"CULT1");
TA_GuidePC (04,00,06,00,"CULT1");
};
func void Rtn_wait4hero_3089 ()
{
TA_Stay (06,00,00,00,"PATH_TO_PLATEAU04");
TA_Stay (00,00,04,00,"PATH_TO_PLATEAU04");
TA_Stay (04,00,06,00,"PATH_TO_PLATEAU04");
};
func void Rtn_defAv_3089 ()
{
TA_Def (06,00,00,00,"BM_ASHTON");
TA_Def (00,00,04,00,"BM_ASHTON");
TA_Def (04,00,06,00,"BM_ASHTON");
};
func void Rtn_camp_3089 ()
{
TA_SitAround (06,00,14,20,"NC_ASHTON");
TA_Boss (14,40,17,00,"NC_ASHTON2");
TA_PlayTune (17,00,22,00,"NC_LO_11"); //fp dodany
TA_Sleep (22,00,06,00,"NC_ASHTON");
};