instance NON_2233_Bula (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Bu³a";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 100;
voice = 1;
id = 666;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0 , 0,"Hum_Head_Bald", 3, 1, GRD_ARMOR_I);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Bastard_04);
EquipItem		(self, ItRw_Crossbow_04);

CreateINVItem		(self, ItWr_Mod_BartholoAssets);
CreateINVItem		(self, ItWr_Mod_BartholoPowerOfAttorney);
CreateINVItem		(self, ItWr_Mod_BartholoSafeConduct);
CreateINVItem		(self, ItWr_Mod_BartholoAct);
CreateINVItem		(self, ItWr_Mod_DisputeAboutRevaran);
CreateINVItem		(self, ItWr_Mod_AboutCastleRevaran);
CreateINVItem		(self, ItWr_HallowedAvengerRepice);

CreateINVItem		(self, Miecz1H1);
CreateINVItem		(self, Miecz1H2);
CreateINVItem		(self, Miecz1H3);
CreateINVItem		(self, Miecz1H4);
CreateINVItem		(self, Miecz1H5);
CreateINVItem		(self, Miecz1H6);
CreateINVItem		(self, Miecz1H7);
CreateINVItem		(self, Miecz1H8);
CreateINVItem		(self, Miecz1H9);
CreateINVItem		(self, Miecz1H10);
CreateINVItem		(self, Miecz1H11);
CreateINVItem		(self, Miecz1H12);
CreateINVItem		(self, Miecz1H13);
CreateINVItem		(self, Miecz1H14);
CreateINVItem		(self, Miecz1H15);
CreateINVItem		(self, URIZIEL_TOUCH);
CreateINVItem		(self, Miecz1H17);
CreateINVItem		(self, Miecz1H18);

CreateINVItem		(self, ItMw_2H_Axe_Big_01);
CreateINVItem		(self, ItMw_2H_Axe_Big_02);
CreateINVItem		(self, ItMw_2H_Axe_Big_03);
CreateINVItem		(self, ItMw_2H_Axe_Big_04);
CreateINVItem		(self, ItMw_2H_Axe_Big_05);
CreateINVItem		(self, ItMw_2H_Axe_Big_06);

CreateINVItem		(self, ItMw_2H_Sword_New_01);
CreateINVItem		(self, ItMw_2H_Sword_New_02);
CreateINVItem		(self, ItMw_2H_Sword_New_03);
CreateINVItem		(self, ItMw_2H_Sword_New_04);
CreateINVItem		(self, ItMw_2H_Sword_New_05);
CreateINVItem		(self, ItMw_2H_Sword_New_06);

CreateINVItem		(self, ItMw_2H_Sword_Old_02);
CreateINVItem		(self, ItMw_2h_Axe_Lumber_01);
CreateINVItem		(self, ItMw_2h_Hammer_War_01);
CreateINVItem		(self, ItMw_2h_Sword_Solid_01);
//lol
CreateINVItem		(self, ItMw_Meisterdegen);
CreateINVItem		(self, ItMw_Addon_BanditTrader);
CreateINVItem		(self, ItMw_Rapier);
CreateINVItem		(self, ItMw_Dagger);
//gacie
CreateINVItem		(self, VLK_ARMOR_H);
CreateINVItem		(self, SFB_ARMOR_DARK);
CreateINVItem		(self, GRAVO_ARMOR);
CreateINVItem		(self, HEREK_ARMOR);
CreateINVItem		(self, SFB_ARMOR_M);

CreateINVItem		(self, NON_HunterArmor_02);
CreateINVItem		(self, NON_HunterArmor_01);

CreateINVItem		(self, HUN_ARMOR_H);
CreateINVItem		(self, GRD_ARMOR_M);
CreateINVItem		(self, HUN_ARMOR_L);
CreateINVItem		(self, NON_LEATHER_ARMOR_L);
CreateINVItem		(self, PodroznikArmor);

CreateINVItem		(self, DarkArmor_v1);
CreateINVItem		(self, DarkArmor_v2);
CreateINVItem		(self, DarkArmor_v3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_666;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_666 ()
{
TA_Cook (06,00,18,00,"W_DUPIE");
TA_Cook (18,00,06,00,"W_DUPIE");
};
