instance NON_2037_Samuel (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Samuel";
Npctype = Npctype_Main;
guild = GIL_VLK;
level = 5;
voice = 5;
id = 2037;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 10;
attribute[ATR_DEXTERITY] = 10;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 70;
attribute[ATR_HITPOINTS] = 70;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Pony", 43,  3,VLK_ARMOR_L);

B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Short_02);
CreateInvItems  (self,ItMiNugget,300);
CreateInvItems  (self,ItLsTorch,10);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,10);
CreateInvItems  (self,ItMi_Stuff_Cup_01,10);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,3);
CreateInvItems  (self,ItFoApple,15);
CreateInvItems  (self,ItFoMutton,15);
CreateInvItems  (self,ItFo_Potion_Water_01,15);
CreateInvItems  (self,ItMiScoop,1);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_2037;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2037 ()
{
TA_Cook (06,00,13,44,"OC_KARCZMA_KOCIOL");
TA_SitAround (13,44,16,32,"GRAJEK");
TA_Cook (16,32,18,00,"OC_KARCZMA_KOCIOL");
TA_SitAround (18,00,06,00,"GRAJEK");
};
