instance NON_4005_MadNovize (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = NAME_MadNovice;
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 35;
voice = 7;
id = 4005;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 50;
attribute[ATR_MANA] = 50;
attribute[ATR_HITPOINTS_MAX] = 120;
attribute[ATR_HITPOINTS] = 120;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Psionic",15, 0,DarkNovize_Armor_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Staff_01);
CreateInvItems  (self,ItMijoint_1,1);
CreateInvItems  (self,ItMi_Amulet_Psi_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_4005;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_4005 ()
{
TA_Pray (06,00,18,00,"POGAN1");
TA_Pray (18,00,06,00,"POGAN1");
};