instance NON_2706_osko (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Osko";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 60;
voice = 8;
id = 2706;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 150;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",55, 1,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, Miecz2H5);
EquipItem		(self, ItRw_Crossbow_04);
CreateInvItems  (self,ItAt_Waran_01,2);
CreateInvItems  (self,ItAt_Lurker_01,2);
CreateInvItems  (self,ItFo_wineberrys_01,3);
CreateInvItems  (self,ItMiNugget,356);
CreateInvItems  (self,ItMi_Stuff_Barbknife_01,3);
CreateInvItems  (self,ItMi_Plants_Swampherb_01,5);
CreateInvItems  (self,ItFoMutton,33);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_2706;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2706 ()
{
TA_PracticeSword (07,55,12,12,"LOCATION_02_14");
TA_SitAround (12,12,18,00,"HUNTERS_BENCH2");
TA_Stand (18,00,21,35,"LOCATION_02_06");
TA_Sleep (21,35,07,55,"LOCATION_02_06");
};
FUNC VOID Rtn_cava_2706 ()
{
TA_Boss (06,00,12,12,"OW_SAWHUT_MOLERAT_SPAWN01");
TA_PracticeSword (12,12,18,00,"OW_SAWHUT_MOLERAT_MOVEMENT2");
TA_Stand (18,00,20,21,"OW_CAVALORN_01"); //nie wiem czy się nie będzie gryźć z rutyną skorpiona
TA_PlayTune (20,21,06,00,"OW_CAVALORN_01");//fp dodany
};
FUNC VOID Rtn_wait_2706 ()
{
TA_Smalltalk (06,00,12,12,"KEMP2");
TA_Smalltalk (12,12,18,00,"KEMP2");
TA_Stand (18,00,20,21,"KEMP2");
TA_Smalltalk (20,21,06,00,"KEMP2");
};
FUNC VOID Rtn_atak_2706 ()
{
TA_PracticeSword (06,00,12,12,"LOWCA2");
TA_PracticeSword (12,12,18,00,"LOWCA2");
TA_Stand (18,00,20,21,"LOWCA2");
TA_Stand (20,21,06,00,"LOWCA2");
};
FUNC VOID Rtn_burdel_2706 ()
{
TA_FollowPC (06,00,12,12,"LOWCA2");
TA_FollowPC (12,12,18,00,"LOWCA2");
TA_FollowPC (18,00,20,21,"LOWCA2");
TA_FollowPC (20,21,06,00,"LOWCA2");
};
func void rtn_lowcaPoszukiwaczy_2706 ()
{
TA_Smalltalk (04,00,12,12,"KEMP2");
TA_Smalltalk (12,12,18,00,"KEMP2");
TA_Stand (18,00,00,00,"KEMP2");
TA_Smalltalk (00,21,04,00,"LOWCAX4");
};