instance NON_3924_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Nowicjusz - rabuœ";
Npctype = Npctype_Main;
guild = GIL_DMB;
level = 10;
voice = 6;
id = 3924;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 40;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 120;
attribute[ATR_HITPOINTS] = 120;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 79,  1,NOV_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMwZ_1H_Sword_01);
CreateInvItems  (self,ItAt_Teeth_01,3);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItForice,1);
CreateInvItems  (self,ItFoBooze,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItKeLockpick,1);
CreateInvItems  (self,ItMijoint_1,3);
CreateInvItems  (self,ItMiNugget,20);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_3924;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3924 ()
{
TA_SitCampfire (00,00,12,00,"CAVE_BANDIT_2");
TA_SitCampfire (12,00,00,00,"CAVE_BANDIT_2");
};
