instance NON_3073_Czarny_Mag (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Nekromanta Isenthor";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 750;
voice = 15;
id = 3073;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 500;
attribute[ATR_DEXTERITY] = 500;
attribute[ATR_MANA_MAX] = 3000;
attribute[ATR_MANA] = 3000;
attribute[ATR_HITPOINTS_MAX] = 1200;
attribute[ATR_HITPOINTS] = 1200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1 ,"Hum_Head_Bald", 30,  2, ISENTHOR_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_MAGE,6);

//----------Ekwipunek----------

CreateInvItems  (self,ItArRuneThunderball,1);
CreateInvItems  (self,ItArScrollfirerain,3);
CreateInvItems  (self,ItArScrollArmyOfDarkness,3);
CreateInvItems  (self,ItMiNugget,50);
CreateInvItems  (self,ItFo_Potion_Mana_01,3);
CreateInvItems  (self,ItAt_BlackMageTrofeum,1);

//kluczowy przedmiot 
CreateInvItems  (self,Focus_Corristo,1);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Mage;
daily_routine = Rtn_start_3073;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_3073 ()
{
TA_StayIgnoring (06,00,18,00,"VM_MAGE");
TA_StayIgnoring (18,00,06,00,"VM_MAGE");
};
