instance NOV_5080_Nowicjusz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Pomocnik Ghorana";
Npctype = Npctype_Ambient;
guild = GIL_NOV;
level = 7;
voice = 3;
id = 5080;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 20;
attribute[ATR_DEXTERITY] = 20;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 70;
attribute[ATR_HITPOINTS] = 70;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Psionic",75, 1,NOV_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Hatchet_01);
CreateInvItems  (self,ItFoWine,3);
CreateInvItems  (self,ItFo_wineberrys_01,8);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Water_01,7);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_5080;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5080 ()
{
TA_PickRice (06,00,17,30,"WINNICA5");
TA_Stand	 (17,30,22,00,"WINNICA_STOLIK1");
TA_Smoke	 (22,00,06,00,"WINNICA_STOLIK1");
};
