instance NOV_5005_Uciekinier (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Uciekinier";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 5;
voice = 1;
id = 5005;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 13;
attribute[ATR_DEXTERITY] = 13;
attribute[ATR_MANA_MAX] = 13;
attribute[ATR_MANA] = 13;
attribute[ATR_HITPOINTS_MAX] = 70;
attribute[ATR_HITPOINTS] = 70;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Psionic",26, 1,NOV_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Nailmace_01);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMuttonRaw,1);
//CreateInvItems  (self,powerAmulett,1);
//CreateInvItems  (self,powerRing,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_5005;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5005 ()
{
TA_Smoke (06,00,18,00,"BIJACZ");
TA_Smoke (18,00,06,00,"BIJACZ");
};
