instance NOV_9001_Ghoran (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Ghoran";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 15;
voice = 1;
id = 9001;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 40;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Psionic",15, 0,NOV_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Hatchet_01);
CreateInvItems  (self,ItMi_Stuff_Amphore_01,3);
CreateInvItems  (self,ItMi_Alchemy_Alcohol_01,5);
CreateInvItems  (self,ItFo_wineberrys_01,40);
CreateInvItems  (self,ItFoWine,7);
CreateInvItems  (self,ItFo_Potion_Water_01,7);
CreateInvItems  (self,ItMiNugget,240);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_9001;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_9001 ()
{
TA_Guard (08,00,12,00,"GHORAN");
TA_HerbAlchemy (12,00,13,05,"WINNICA_STANOWISKO2");
TA_Stand (13,05,14,30,"WINNICA_STOLIK2");
TA_SitAround (14,30,17,00,"WINNICA_BENCH1");
TA_Smoke (17,00,20,30,"WINNICA_STOLIK2");
TA_Stand (20,30,08,00,"WINNICA_STOLIK2");
};
