/*
Piraci - Gothic:Edycja rozszerzona
Skrypty NPC
Rozdzia³ 4
26 lipiec 2012
*/

instance NON_5026_Pirat3 (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Szerszeñ"; //Hank
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 52;
voice = 1;
id = 5026;
flags		=	NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 114;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//				body mesh,				head mesh,				hairmesh,	face-tex,	hair-tex,	skin	
	Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_FatBald", 48 , 1, Pirat2Armor);
	
	B_Scale (self);
	Mdl_SetModelFatness (self, 0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, Kordelas);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,4);
CreateInvItems  (self,ItFoWine,4);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,1);
CreateInvItems  (self,ItMi_Stuff_Barbknife_01,3);
CreateInvItems  (self,ItMi_Stuff_Cup_02,1);
CreateInvItems  (self,ItMi_Stuff_Amphore_01,1);
CreateInvItems  (self,ItFo_Fish,10);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5026;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5026 ()
{
	TA_SitCampfire		(22,00,08,00,"PIRAT3");
	TA_SitCampfire		(08,00,22,00,"PIRAT3");
};
FUNC VOID Rtn_follow_5026 ()
{
	TA_FolloWPC		(22,00,08,00,"PIRAT3");
	TA_FolloWPC		(08,00,22,00,"PIRAT3");
};

FUNC VOID Rtn_morok_5026 ()
{
	TA_Boss (09,00,12,45,"MOROK3");
	TA_Stand (12,45,15,22,"MOROK3");
	TA_Boss (15,22,18,00,"MOROK3");
	TA_SitAround (18,00,09,00,"MOROK4");
};

instance NON_5027_Pirat4 (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Gordon"; //Rodney
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 52;
voice = 1;
id = 5027;
flags		=	NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 114;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex,teethtex,ruestung	
	Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 0,"Hum_Head_Fighter", 1,  2, GORDON_ARMOR);
        
	B_Scale (self);
    	Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, Kordelas);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,4);
CreateInvItems  (self,ItFoWine,4);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,1);
CreateInvItems  (self,ItMi_Stuff_Barbknife_01,3);
CreateInvItems  (self,ItMi_Stuff_Cup_02,1);
CreateInvItems  (self,ItMi_Stuff_Amphore_01,1);
CreateInvItems  (self,ItFo_Fish,33);
CreateInvItems  (self,ItFoChesseSoup,10);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5027;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5027 ()
{
	TA_Stand		(22,00,08,00,"PIRAT1");
	TA_Stand		(08,00,22,00,"PIRAT1");
};

FUNC VOID Rtn_follow_5027 ()
{
	TA_FolloWPC		(22,00,08,00,"PIRAT1");
	TA_FolloWPC		(08,00,22,00,"PIRAT1");
};

FUNC VOID Rtn_morok_5027 ()
{
	TA_SitAround		(22,00,08,00,"MOROK");
	TA_SitAround		(08,00,22,00,"MOROK");
};

instance NON_5024_Pirat1 (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Hark"; //Rick
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 52;
voice = 1;
id = 5024;
flags		=	NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 114;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 19,  1, PiratArmor);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_Light_01);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,4);
CreateInvItems  (self,ItFoWine,4);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,1);
CreateInvItems  (self,ItMi_Stuff_Barbknife_01,3);
CreateInvItems  (self,ItMi_Stuff_Cup_02,1);
CreateInvItems  (self,ItMi_Stuff_Amphore_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5024;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5024 ()
{
	TA_SitCampfire		(22,00,08,00,"OW_PATH_201");
	TA_SitCampfire		(08,00,22,00,"OW_PATH_201");
};
FUNC VOID Rtn_follow_5024 ()
{
	TA_FolloWPC		(22,00,08,00,"OW_PATH_201");
	TA_FolloWPC		(08,00,22,00,"OW_PATH_201");
};

FUNC VOID Rtn_morok_5024 ()
{
	TA_SitCampfire (09,00,12,45,"PIPL2");
	TA_Stand (12,45,15,22,"PIPL2");
	TA_PracticeSword (15,22,18,00,"PIPL2");
	TA_PlayTune (18,00,09,00,"PIPL2"); //fp dodany
};

instance NON_5025_Pirat2 (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Steve"; //Angus
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 52;
voice = 1;
id = 5025;
flags		=	NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 114;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex,teethtex,ruestung	
	Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Bald",8, 1,Pirat2Armor);
	//Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1 ,"Hum_Head_Bald", 117,  2, );

	B_Scale (self);
	Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, Kordelas);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,4);
CreateInvItems  (self,ItFoWine,4);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,1);
CreateInvItems  (self,ItMi_Stuff_Barbknife_01,3);
CreateInvItems  (self,ItMi_Stuff_Cup_02,1);
CreateInvItems  (self,ItMi_Stuff_Amphore_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5025;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5025 ()
{
	TA_SitCampfire		(22,00,08,00,"PIRAT2");
	TA_SitCampfire		(08,00,22,00,"PIRAT2");
};

FUNC VOID Rtn_follow_5025 ()
{
	TA_FolloWPC		(22,00,08,00,"PIRAT2");
	TA_FolloWPC		(08,00,22,00,"PIRAT2");
};

FUNC VOID Rtn_morok_5025 ()
{
	TA_skrzynka (09,00,12,45,"PIPL1");
TA_PracticeSword (12,45,15,22,"PIPL3");
TA_Stand (15,22,18,00,"PIPL3");
TA_Sleep (18,00,09,00,"SPAC2");
};