instance VLK_7050_Robol (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Torkel";
Npctype = Npctype_MAIN;
guild = GIL_VLK;
level = 5;
voice = 1;
id = 7050;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 60;
attribute[ATR_HITPOINTS] = 60;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",3,1,"Hum_Head_Fighter", 70,  3, VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
CreateInvItems  (self,ItKeLockpick,10);
CreateInvItems  (self,ItMiHammer,10);
CreateInvItems  (self,ItMiSwordblade,5);
CreateInvItems  (self,ItFoApple,10);
CreateInvItems  (self,ItFoMutton,23);
CreateInvItems  (self,ItFosoup,12);
CreateInvItems  (self,ItFoBooze,12);
CreateInvItems  (self,ItFo_Fish,12);
CreateInvItems  (self,ItFo_Honey,5);
CreateInvItems  (self,ItMwPickaxe,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_7050;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7050 ()
{
TA_RepairHut (06,00,22,00,"PO1");
TA_SmallTalk (22,00,06,00,"PO1T");
};
instance VLK_7051_Robol (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Robotnik";
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 5;
voice = 2;
id = 7051;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 60;
attribute[ATR_HITPOINTS] = 60;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Bald", 68,  1, VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
CreateInvItems  (self,ItKeLockpick,10);
CreateInvItems  (self,ItMiHammer,10);
CreateInvItems  (self,ItMiSwordblade,5);
CreateInvItems  (self,ItFoApple,10);
CreateInvItems  (self,ItFoMutton,23);
CreateInvItems  (self,ItFosoup,12);
CreateInvItems  (self,ItFoBooze,12);
CreateInvItems  (self,ItFo_Fish,12);
CreateInvItems  (self,ItFo_Honey,5);
CreateInvItems  (self,ItMwPickaxe,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_7051;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7051 ()
{
TA_RepairHut (06,00,22,00,"PO2");
TA_SmallTalk (22,00,06,00,"PO2T");
};
