instance SLD_2805_Najemnik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = Name_Soeldner;
Npctype = Npctype_Ambient;
guild = GIL_SLD;
level = 40;
voice = 11;
id = 2805;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 130;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_FatBald",1, 1,SLD_ARMOR_HUN);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_War_02);
EquipItem		(self, ItRw_Bow_Long_07);
CreateInvItems  (self,ItMiNugget,300);
CreateInvItems  (self,ItMi_Stuff_OldCoin_01,300);
CreateInvItems  (self,ItMi_Stuff_Cup_02,2);
CreateInvItems  (self,ItFo_Potion_Health_01,3);
CreateInvItems  (self,ItFoMuttonRaw,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_2805;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2805 ()
{
TA_WorkMOB (08,30,11,25,"SLD_HTS_WORK");
TA_Smoke (11,25,12,30,"SLD_HTS_PREPARE");
TA_skrzynka (12,30,13,05,"SLD_HTS_CHEST");
TA_Boss (13,05,14,30,"SLD_HTS_BOSS");
TA_WorkMOB (14,30,18,45,"SLD_HTS_WORK");
TA_SitCampfire (18,45,22,55,"SLD_HTS_CAMP3");
TA_Sleep (22,55,08,30,"SLD_HTS_BED2");
};

FUNC VOID Rtn_FMCstart_2805()
{
	TA_Guard	(01,00,13,00,	"FMC_ENTRANCE");
	TA_Guard 	(13,00,01,00,	"FMC_ENTRANCE");
};