instance SLD_2803_Outlam (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Outlam";
Npctype = Npctype_Main;
guild = GIL_SLD;
level = 40;
voice = 10;
id = 2803;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 350;
attribute[ATR_HITPOINTS] = 350;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1,"Hum_Head_Pony", 48, 1,SLD_ARMOR_HUN);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,8);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Bastard_02);
EquipItem		(self, ItRw_Bow_Long_06);
CreateInvItems  (self,ItMiNugget,350);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,2);
CreateInvItems  (self,ItMi_Stuff_Plate_01,1);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,1);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Teeth_01,53);
CreateInvItems  (self,ItMw_1H_Mace_Light_01,1);
//trade
	CreateInvItems (self, ItMi_Stuff_Barbknife_01, 5);
    CreateInvItems (self, ItMi_Stuff_Cup_01, 1);
    CreateInvItems (self, ItMi_Alchemy_Sulphur_01, 5);
    CreateInvItems (self, Schutzamulett_Geschosse, 1);
    CreateInvItems (self, ItAt_Teeth_01, 5);
    CreateInvItems (self, ItAt_Wolf_01, 3);
    CreateInvItems (self, ItAt_Lurker_02, 2);
    CreateInvItems (self, ItFo_Potion_Health_01, 2);
    CreateInvItems (self, ItFoMutton, 35);
    CreateInvItems (self, Schutzring_Geschosse1, 1);
    CreateInvItems (self, ItFo_Plants_Berrys_01, 25);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2803;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2803 ()
{
TA_SitAround (06,00,11,25,"SLD_HTS_BENCH1");
TA_WorkMOB (11,25,14,30,"SLD_HTS_WORK");
TA_WashSelf (14,30,14,55,"SLD_HTS_PREPARE");//SLD_HTS_CHEST
TA_Skrzynka (14,55,15,20,"SLD_HTS_CHEST");
TA_Stand (15,20,17,40,"SLD_HTS_PREPARE");
TA_Boss (17,30,19,30,"SLD_HTS_BOSS");
TA_SitAround (19,30,23,48,"SLD_HTS_BENCH1");
TA_Sleep (23,48,06,00,"SLD_HTS_BED5");
};

FUNC VOID Rtn_FMCstart_2803 ()
{
	TA_GuardPalisade	(01,00,13,00, "FMC_PATH07");
	TA_GuardPalisade	(13,00,01,00, "FMC_PATH07");
};
