instance SLD_2801_Soldier (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = Name_Soeldner;
Npctype = Npctype_Ambient;
guild = GIL_SLD;
level = 20;
voice = 11;
id = 2801;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 65;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 350;
attribute[ATR_HITPOINTS] = 350;

	//-------- visuals --------
	// 				animations
	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//				body mesh,				head mesh,				hairmesh,	face-tex,	hair-tex,	skin	
	Mdl_SetVisualBody (self,"hum_body_Naked0",1, 3,"Hum_Head_FatBald", 9, 2,SLD_ARMOR_HUN);
	
	B_Scale (self);
	Mdl_SetModelFatness (self, 0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_Old_01);
EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItMiNugget,120);
CreateInvItems  (self,ItMi_Stuff_Pipe_01,2);
CreateInvItems  (self,ItMi_Stuff_Plate_01,1);
CreateInvItems  (self,ItMiScoop,1);
CreateInvItems  (self,ItMi_Stuff_Silverware_01,1);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,1);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Teeth_01,53);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2801;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2801 ()
{
TA_Cook (07,25,09,40,"SLD_HTS_COOK");
TA_Smoke (09,40,11,15,"SLD_HTS_COOK");
TA_Cook (11,15,13,30,"SLD_HTS_COOK");
TA_SitCampfire (13,20,15,40,"SLD_HTS_CAMP3");
TA_SitCampfire (15,40,17,20,"SLD_HTS_CAMP3"); //do zmiany
TA_Cook (17,20,19,30,"SLD_HTS_COOK");
TA_StandAround (19,30,22,40,"SLD_HTS_BENCH2");
TA_Sleep (22,40,07,25,"SLD_HTS_BED1");
};
