instance VLK_5090_Tragaz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Tragarz";
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 5;
voice = 1;
id = 5090;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 60;
attribute[ATR_HITPOINTS] = 60;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Bald", 68,  1, VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_5090;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5090 ()
{
TA_SitCampfire (06,00,22,00,"KON4");
TA_SitCampfire (22,00,06,00,"KON4");
};
FUNC VOID Rtn_las_5090 ()
{
TA_Stay (22,00,06,00,"PACHOL3");
TA_Stay (06,00,22,00,"PACHOL3");
};
FUNC VOID Rtn_follow_5090 ()
{
TA_FollowPC (06,00,22,00,"OC1");
TA_FollowPC (22,00,06,00,"OC1");
};
FUNC VOID Rtn_camp_5090 ()
{
TA_Stand (22,00,06,00,"DOSTAWA3");
TA_Stand (06,00,22,00,"DOSTAWA3");
};