instance VLK_7003_Abel (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Abel";
Npctype = Npctype_Main;
guild = GIL_VLK;
level = 3;
voice = 12;
id = 7003;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 20;
attribute[ATR_DEXTERITY] = 20;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 80;
attribute[ATR_HITPOINTS] = 80;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",1, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
//Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Hatchet_01);
//EquipItem		(self, ItRw_Bow_Small_01);
CreateInvItems  (self,ItFoMutton,5);
CreateInvItems  (self,ItForice,2);
CreateInvItems  (self,Schutzring_Feuer1,1);
CreateInvItems  (self,ItKeLockpick,5);
CreateInvItems  (self,ItMiHammer,1);
CreateInvItems  (self,ItLsTorch,3);
CreateInvItems  (self,ItMiNugget,12);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_7003;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_back_7003 ()
{
TA_HerbAlchemy (06,00,22,00,"ROBOL1");
TA_Stand (22,00,06,00,"ROBOL1");
TA_PracticeSword (06,00,12,00,"BACK1");
TA_Boss (12,00,16,00,"BACK1");
TA_Sleep (16,00,18,00,"HELP1");
TA_SitCampfire (18,00,22,00,"HELP1");
TA_Stay (22,00,06,00,"HELP1");
};

FUNC VOID Rtn_start_7003 ()
{
TA_HerbAlchemy (06,00,22,00,"ROBOL1");
TA_Stay (22,00,06,00,"ROBOL1");
};

FUNC VOID Rtn_run_7003 ()
{
TA_Stand (06,00,22,00,"OW_PATH_266");
TA_Stand (22,00,06,00,"OW_PATH_266");
};

FUNC VOID Rtn_psi_7003 ()
{
TA_Stand (05,45,12,35,"WINNICA_STOLIK1");
TA_PICKRICE (12,35,16,12,"WINNICA3");
TA_SMOKE (16,12,19,35,"PSI_PATROS_CLIENT2");
TA_SLEEP (19,35,05,45,"PSI_19_HUT_IN");
};
