instance VLK_7009_kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = Name_Buddler;
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 5;
voice = 1;
id = 7009;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 10;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",0, 0,VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
CreateInvItems  (self,ItAt_Meatbug_01,2);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItForice,3);
CreateInvItems  (self,ItMiNugget,5);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_7009;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7009 ()
{
TA_PickOre (06,00,13,00,"KOP3");
TA_Stand (13,00,14,00,"KOP3");
TA_SitCampfire (14,00,06,00,"KOP3");
};
