instance VLK_5056_Tragarz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Tragarz";
Npctype = Npctype_Main;
guild = GIL_VLK;
level = 10;
voice = 4;
id = 5056;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 20;
attribute[ATR_DEXTERITY] = 20;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 35;
attribute[ATR_HITPOINTS] = 35;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",0, 0,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_5056;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5056 ()
{
TA_Stay (06,00,18,00,"ESKORTA4");
TA_Stay (18,00,06,00,"ESKORTA4");
};
/*
FUNC VOID Rtn_start_5056 ()
{
TA_Stand (06,00,18,00,"DOSTAWA1");
TA_Stand (18,00,06,00,"DOSTAWA1");
};*/