instance VLK_3936_OpetanyKopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Opêtany kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 6;
id = 3936;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",3, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Axe_Old_01);
CreateInvItems (self, StoneOfKnowledge, 1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3936;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3936 ()
{
TA_smoke (00,00,12,00,"JOSEP2");
TA_smoke (12,00,00,00,"JOSEP2");
};

instance VLK_3937_OpetanyKopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Opêtany kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 6;
id = 3937;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",3, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Axe_Old_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3937;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3937 ()
{
TA_smoke (00,00,12,00,"KOPACZ_ZBIR3");
TA_smoke (12,00,00,00,"KOPACZ_ZBIR3");
};

instance VLK_3938_OpetanyKopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Opêtany kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 6;
id = 3938;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",3, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Axe_Old_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3938;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3938 ()
{
TA_smoke (00,00,12,00,"KOPACZ_ZBIR2");
TA_smoke (12,00,00,00,"KOPACZ_ZBIR2");
};

instance VLK_3939_OpetanyKopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Opêtany kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 6;
id = 3939;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",3, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Axe_Old_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3939;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3939 ()
{
TA_smoke (00,00,12,00,"KOPACZ_ZBIR1");
TA_smoke (12,00,00,00,"KOPACZ_ZBIR1");
};