instance VLK_7010_kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = Name_Buddler;
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 6;
voice = 2;
id = 7010;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 10;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",0, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_Light_01);
CreateInvItems  (self,ItAt_Meatbug_01,2);
CreateInvItems  (self,ItForice,3);
CreateInvItems  (self,ItMiNugget,5);
CreateInvItems  (self,ItFo_wineberrys_01,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_7010;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7010 ()
{
TA_PickOre (06,00,15,22,"KOP1");
TA_Smoke (15,22,16,00,"KOP2");
TA_SitCampfire (16,00,22,20,"KOP2");
TA_Stand (22,20,06,00,"KOP1");
};
