instance NON_5635_Will (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Will";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 40;
voice = 11;
id = 5635;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0 , 0,"Hum_Head_Bald", 3, 1, SFB_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, Miecz2H2);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,50);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5635;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5635 ()
{
TA_SitAround (00,00,13,33,"GOLDMAN1");
TA_Smoke (13,33,15,10,"GOLDMAN1");
TA_Sitaround (15,10,00,00,"GOLDMAN1");
};
FUNC VOID Rtn_guide_5635 ()
{
TA_GuidePC (00,00,13,33,"OW_PATH_07_15_CAVE2");
TA_GuidePC (13,33,15,10,"OW_PATH_07_15_CAVE2");
TA_GuidePC (15,10,00,00,"OW_PATH_07_15_CAVE2");
};

FUNC VOID Rtn_mine_5635 ()
{
TA_Boss (00,00,13,33,"OW_PATH_07_15_CAVE3");
TA_Smoke (13,33,15,10,"OW_PATH_07_15_CAVE3");
TA_StandAround (15,10,00,00,"OW_PATH_07_15_CAVE3");
};
instance NON_5636_Thompson (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Thompson";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 40;
voice = 11;
id = 5636;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 85;
attribute[ATR_DEXTERITY] = 85;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_Bald",38 ,  4, VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_04);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,200);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5636;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5636 ()
{
TA_Stand (03,00,13,33,"THOMPSON");
TA_Smoke (13,33,15,10,"THOMPSON");
TA_Stand (15,10,20,35,"THOMPSON");
TA_StandDrunk (20,35,03,00,"THOMPSON");
};
FUNC VOID Rtn_guide_5636 ()
{
TA_GuidePC (00,00,13,33,"LOCATION_15_IN_2");
TA_GuidePC (13,33,15,10,"LOCATION_15_IN_2");
TA_GuidePC (15,10,00,00,"LOCATION_15_IN_2");
};