instance BAU_2015_Josh (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Josh";
Npctype = Npctype_Main;
guild = GIL_BAU;
level = 48;
voice = 3;
id = 2015;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Bald",112, 1,ORG_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Short_02);
EquipItem		(self, ItRw_Bow_Small_03);
CreateInvItems  (self,ItFoApple,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2015;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2015 ()
{
TA_Stay (06,00,18,00,"WAR1");
TA_Stay (18,00,06,00,"WAR1");
};
FUNC VOID Rtn_wait_2015 ()
{
TA_Stand (06,00,18,00,"OW_PATH_1_5_A");
TA_Stay (18,00,06,00,"OW_PATH_1_5_A");
};
FUNC VOID Rtn_atak_2015 ()
{
TA_FollowPC (06,00,18,00,"OW_PATH_1_5_A");
TA_FollowPC (18,00,06,00,"OW_PATH_1_5_A");
};