instance GRD_2017_Artch (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Artch";
	Npctype			= NPCTYPE_FRIEND;
guild = GIL_GRD;
level = 50;
voice = 6;
id = 2017;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Fighter",98, 1,GRD_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Bastard_01);
EquipItem		(self, ItRw_Crossbow_03);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFo_Potion_Health_01,5);
CreateInvItems  (self,ItKeLockpick,5);
CreateInvItems  (self,ItMiNugget,130);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2017;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2017 ()
{
TA_Guard (06,00,18,00,"GRD7");
TA_Guard (18,00,22,00,"GRD7");
TA_Smoke (22,00,06,00,"GRD7");
};
FUNC VOID Rtn_ded_2017 ()
{
TA_Guard (06,00,18,00,"WAR6");
TA_Guard (18,00,22,00,"WAR6");
TA_Smoke (22,00,06,00,"WAR6");
};