instance GRD_7006_Joel (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Joel";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 14;
voice = 8;
id = 7006;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 55;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 180;
attribute[ATR_HITPOINTS] = 180;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 3,"Hum_Head_Fighter",1, 3,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
CreateInvItems  (self,ItAt_Teeth_01,13);
CreateInvItems  (self,STT_ARMOR_M,1);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFocheese,2);
CreateInvItems  (self,ItFoBeer,1);
CreateInvItems  (self,ItFoWine,2);
CreateInvItems  (self,ItMiNugget,6);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_7006;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7006 ()
{
TA_WorkMOB 			(06,35,13,00,"OMC_SHARP");
TA_SitCampfire 		(13,00,15,15,"GRD1");
TA_CookforMe 		(15,15,16,37,"OMC_SMALL_PAN");
TA_Boss		 		(16,37,20,11,"OMC_HUT_JOEL");
TA_Sleep		 	(20,11,06,35,"OMC_BED_JOEL");
};

//////////////////////////////////////////////////////
// ZADANIE: SKARB STAREGO STRAŻNIKA
//////////////////////////////////////////////////////
FUNC VOID Rtn_joshkiller_2015 ()
{
TA_Stay (06,00,18,00,"WAR1");
TA_Stay (18,00,06,00,"WAR1");
};

//////////////////////////////////////////////////////
// ZADANIE: SKARB STAREGO STRAŻNIKA
//////////////////////////////////////////////////////
FUNC VOID Rtn_treasure_7006 ()
{
TA_WorkMOB 			(06,35,13,00,"OMC_SHARP");
TA_SitCampfire 		(13,00,15,15,"GRD1");
TA_CookforMe 		(15,15,16,37,"OMC_SMALL_PAN");
TA_Boss		 		(16,37,20,11,"OMC_HUT_JOEL");
TA_Boss			 	(20,11,01,00,"OW_JOELAWAY");
TA_Sleep		 	(01,00,06,35,"OMC_BED_JOEL");
};

FUNC VOID Rtn_obrona_7006 ()
{
TA_Guard (06,00,18,00,"WAR1");
TA_Guard (18,00,06,00,"WAR1");
};
