instance GRD_2014_Siepacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Siepacz";
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 5;
voice = 15;
id = 2014;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 35;
attribute[ATR_DEXTERITY] = 35;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 100;
attribute[ATR_HITPOINTS] = 100;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",3, 1,"Hum_Head_Fighter",114, 1,STT_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFoBeer,1);
CreateInvItems  (self,ItFo_Plants_Herb_01,1);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
CreateInvItems  (self,ItMiNugget,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2014;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2014 ()
{
TA_Smalltalk (06,00,22,00,"SIEP2");
TA_Stand (22,00,06,00,"SIEP2");
};
FUNC VOID Rtn_follow_2014 ()
{
TA_FollowPC (06,00,12,00,"SIEP2");
TA_FollowPC (12,00,06,00,"SIEP2");
};
FUNC VOID Rtn_away_2014 ()
{
TA_Stay (06,00,12,00,"");
TA_Stay (12,00,06,00,"");
};
