instance GRD_2002_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 13;
voice = 3;
id = 2002;

//----------Statystyki----------

attribute[ATR_STRENGTH] 	= 45;
	attribute[ATR_DEXTERITY] 	= 50;
	attribute[ATR_MANA_MAX] 	= 0;
	attribute[ATR_MANA] 		= 0;
	attribute[ATR_HITPOINTS_MAX]= 200;
	attribute[ATR_HITPOINTS] 	= 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Bald",10, 2,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFocheese,1);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoBeer,1);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2002;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2002 ()
{
TA_Sleep (04,00,09,45,"BED01");
TA_Stand (09,45,15,00,"OW_PATH_1_17");
TA_StandAround (15,00,18,00,"OW_PATH_1_17");
TA_Smalltalk (18,00,04,00,"OW_PATH_1_17");
};

FUNC VOID Rtn_oszust_2002 ()
{
TA_PickRice (06,00,12,00,"ZMYLKA2");
TA_StandAround (12,00,06,00,"ZMYLKA2");
};
FUNC VOID Rtn_bijacz_2002 ()
{
TA_Stay (06,00,12,00,"CAMP01");
TA_Stay (12,00,06,00,"CAMP01");
};