instance GRD_2097_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Ambient;
guild = GIL_GRD;
level = 40;
voice = 8;
id = 2097;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 96;
attribute[ATR_DEXTERITY] = 96;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 0,"Hum_Head_FatBald", 10,  1, GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_War_03);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoCrawlersoup,2);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_2097;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2097 ()
{
TA_GuardPassage (18,00,06,00,"VM_GRD2");
TA_GuardPassage (06,00,18,00,"VM_GRD2");
};
