instance GRD_2001_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Main;
guild = GIL_GRD;
level = 13;
voice = 1;
id = 2001;

//----------Statystyki----------

attribute[ATR_STRENGTH] 		= 45;
	attribute[ATR_DEXTERITY] 	= 50;
	attribute[ATR_MANA_MAX] 	= 0;
	attribute[ATR_MANA] 		= 0;
	attribute[ATR_HITPOINTS_MAX]= 180;
	attribute[ATR_HITPOINTS] 	= 180;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",103, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03_Old);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFoMutton,1);
CreateInvItems  (self,ItForice,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2001;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2001 ()
{
TA_Boss (06,00,16,00,"OW_VM_ENTRANCE");
TA_Stand (16,00,18,00,"OW_PATH_1_17_1");
TA_Smalltalk (18,00,04,00,"OW_PATH_1_16");
TA_SitCampfire (04,00,06,00,"CAMP02");
};
FUNC VOID Rtn_frajer_2001 ()
{
TA_StandAround (06,00,14,00,"ZMYLKA1");
TA_Smoke (14,00,06,00,"ZMYLKA1");
};
FUNC VOID Rtn_bijacz_2001 ()
{
TA_Stand (06,00,14,00,"CAMP02");
TA_Smoke (14,00,06,00,"CAMP02");
};