instance GRD_2291_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stra¿nik";
Npctype = Npctype_Ambient;
guild = GIL_GRD;
level = 30;
voice = 8;
id = 2291;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 90;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",16, 1,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_2291;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2291 ()
{
TA_Guard (06,00,18,00,"OW_PATH_1_17_4");
TA_Guard (18,00,06,00,"OW_PATH_1_17_4");
};
