instance GRD_3917_Elitarny_straznik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Garotnik";
Npctype = Npctype_main;
guild = GIL_GRD;
level = 50;
voice = 7;
id = 3917;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",34, 1,GRD_ARMOR_H2);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Broad_02);
EquipItem		(self, ItRw_Crossbow_04);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3917;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3917 ()
{
TA_Guard (08,00,20,00,"OCC_BARONS_GREATHALL_BERATER");
TA_SitAround (20,00,23,00,"OCR_ARENA_BARONS_HUT_ROOFTOP");
TA_Stand (23,00,00,00,"OCC_BARONS_RIGHT_ROOM_TABLE");
TA_BodyGuard (00,00,08,00,"OCC_BARONS_UPSTAIRS_PROMENADE_RIGHT_CORNER");
};
FUNC VOID Rtn_OT_3917 ()
{
TA_Stand (08,00,20,00,"OCC_CHAPEL_LEFT_STAIRCASE_BOTTOM");
TA_Stand (20,00,08,00,"OCC_CHAPEL_LEFT_STAIRCASE_BOTTOM");
};