instance GRD_2096_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Ambient;
guild = GIL_GRD;
level = 30;
voice = 8;
id = 2096;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",19, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoCrawlersoup,2);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_2096;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2096 ()
{
TA_GuardPassage (06,00,18,00,"VM_GRD3");
TA_GuardPassage (18,00,06,00,"VM_GRD3");
};
