instance GRD_3085_Nek (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Nerwowy Szkodnik";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 15;
voice = 5;
id = 3085;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 180;
attribute[ATR_HITPOINTS] = 180;

//----------Wyglad----------

	//-------- visuals --------
	// 			animations
	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex,teethtex,ruestung	
	Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_Bald", 19,  1, ORG_ARMOR_L);
        
	B_Scale (self);
	Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,5);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,1);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Crossbow_01);
CreateInvItems  (self,ItMiNugget,40);
CreateInvItems  (self,ItMi_Plants_Swampherb_01,2);
CreateInvItems  (self,ItMi_Stuff_Plate_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3085;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3085 ()
{
TA_SitAround (06,00,18,00,"NC_HUT15_IN");
TA_SitAround (18,00,06,00,"NC_HUT15_IN");
};

FUNC VOID Rtn_idziemy_3085 ()
{
TA_FollowPC (18,00,06,00,"SZUKAJCIE_TERAZ_KURWY");
TA_FollowPC (06,00,18,00,"SZUKAJCIE_TERAZ_KURWY");
};

FUNC VOID Rtn_nc_3085 ()
{
TA_SitAround (06,00,13,22,"SLD_HTS_CAMP2");
TA_RepairHut (13,22,17,56,"SLD_HTS_NEK");
TA_SitAround (17,56,06,00,"SLD_HTS_CAMP2");
};
