instance NON_2056_Patrick (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Patrick";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 4;
id = 2056;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Bald",4, 1,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_Light_01);
CreateInvItems  (self,ItFoApple,2);
CreateInvItems  (self,ItFoMutton,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_2056;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2056 ()
{
TA_Stand (06,00,15,00,"KOLEJKA1");
TA_CookForMe (15,00,17,00,"KOLEJKA4");
TA_Stay (17,00,06,00,"KOLEJKA1");
};
FUNC VOID Rtn_uciek_2056 ()
{
TA_Stand (06,00,15,00,"OW_PATH_2_04");
TA_CookForMe (15,00,17,00,"OW_PATH_2_04");
TA_Stay (17,00,06,00,"OW_PATH_2_04");
};