instance NON_3933_Uturiel (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Uturiel";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 30;
voice = 4;
id = 3933;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
	Mdl_SetVisualBody (self,"hum_body_Naked0",1, 0,"Hum_Head_Psionic", 6, 1, KDF_ARMOR_H);

B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_MAGE,6);
Npc_SetTalentSkill (self, NPC_TALENT_2H,9);

//----------Ekwipunek----------
CreateInvItems  (self,ItArRuneFirestorm,1);
CreateInvItems  (self,ItArRuneHeal,1);
CreateInvItems  (self,ItArRuneThunderball,1);
CreateInvItems  (self,ItArRunePyrokinesis,1);
CreateInvItems  (self,ItFosoup,3);
CreateInvItems  (self,ItFoWine,1);
CreateInvItems  (self,ItFoMutton,2);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFo_Potion_Mana_01,10);
CreateInvItems  (self,ItFo_Potion_Health_01,10);
CreateInvItems  (self,ItFo_Potion_Mana_Perma_02,1);
CreateInvItems  (self,Machtvolle_Kunst,1);
CreateInvItems  (self,ItMiFlask,5);
CreateInvItems  (self,ItMiNugget,100);
CreateInvItems  (self,ItLsTorch,3);
CreateInvItems  (self,ItMi_Stuff_OldCoin_01,10);
//CreateInvItems  (self,BlueCrystal,1);
CreateInvItems	(self, ItArRuneTeleportHome, 1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Mage;
daily_routine = Rtn_start_3933;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_3933 ()
{
TA_Sleep (00,00,18,00,"UTRIEL_SLEEP");
TA_PotionAlchemy (18,00,00,00,"UTRIEL_MAG");
};

FUNC VOID Rtn_experiment_3933 ()
{
TA_PracticeMagic 		(00,00,18,00,"OW_MIS_UTURIELEXPERIMENT");
TA_PracticeMagic		(18,00,00,00,"OW_MIS_UTURIELEXPERIMENT");
};

FUNC VOID Rtn_die_3933 ()
{
TA_Die 		(00,00,18,00,"OW_MIS_UTURIELEXPERIMENT");
TA_Die		 (18,00,00,00,"OW_MIS_UTURIELEXPERIMENT");
};