instance NON_2703_MYSLIWY (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Prin";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 60;
voice = 11;
id = 2703;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 130;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 2,"Hum_Head_Bald",5, 2,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_03);
EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,33);
CreateInvItems  (self,ItArScrollLight,2);
CreateInvItems  (self,ItArScrollFirestorm,2);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,500);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2703;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2703 ()
{
TA_WashSelf 	(05,30,06,00,"LOCATION_02_05");
TA_SitCampfire  (06,00,10,45,"HUNTERS_CAMP1");
TA_CookForMe 	(10,45,11,20,"LOCATION_02_08");
TA_Smith_Sharp 		(11,20,12,55,"OW_LOCATION_02_08");
TA_SitCampfire  (12,55,16,00,"HUNTERS_CAMP1");
TA_WorkMOB		(16,00,17,20,"HUNTERS_WORK1");
TA_SitCampfire  (17,20,05,30,"HUNTERS_CAMP1");
};
FUNC VOID Rtn_cava_2703 ()
{
TA_PracticeBow (12,20,15,33,"OW_OLDSAWHUT_PRACTICE_BOW");
TA_SitCampfire(15,33,18,45,"OW_CAVALORN_01");
TA_Boss		  (18,45,06,55,"OW_SAWHUT_MOLERAT_SPAWN01");
TA_WorkMOB	 (06,55,11,00,"OW_SAWHUT_MOLERAT_MOVEMENT5");
TA_Stand	 (11,00,12,20,"OW_SAWHUT_MOLERAT_MOVEMENT4"); 
};
FUNC VOID Rtn_wait_2703 ()
{
TA_Stand (06,00,18,33,"LOWCA4");
TA_Smoke (18,33,06,00,"LOWCA4");
};
FUNC VOID Rtn_atak_2703 ()
{
TA_Stand (06,00,18,33,"LOWCA5");
TA_Smoke (18,33,06,00,"LOWCA5");
};
FUNC VOID Rtn_burdel_2703 ()
{
TA_FollowPC (06,00,18,33,"LOWCA5");
TA_FollowPC (18,33,06,00,"LOWCA5");
};