instance NON_2701_Straznik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Garett";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 55;
voice = 3;
id = 2701;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 130;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",68, 1,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,1);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_01);
EquipItem		(self, ItRw_Bow_War_02);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,33);
CreateInvItems  (self,ItAt_Shadow_02,2);
CreateInvItems  (self,ItArScrollLight,2);
CreateInvItems  (self,ItArScrollFirestorm,2);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,344);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_2701;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2701 ()
{
TA_Boss (06,00,15,00,"LOCATION_02_11");
TA_Stand (15,00,16,33,"LOCATION_02_11");
TA_Boss (16,33,21,20,"LOCATION_02_11");
TA_SitCampfire (21,20,06,00,"LOCATION_02_11");
};
FUNC VOID Rtn_cavalorn_2701 ()
{
TA_SitAround (18,55,17,25,"OW_SAWHUT_BENCH1");
TA_PracticeSword (17,25,18,55,"PATH_OC_NC_4");
};
