instance NON_3078_Avallach (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Avallach";
Npctype = Npctype_Main;
guild = GIL_SLD;
level = 70;
voice = 8;
id = 3078;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 300;
attribute[ATR_DEXTERITY] = 300;
attribute[ATR_MANA_MAX] = 200;
attribute[ATR_MANA] = 200;
attribute[ATR_HITPOINTS_MAX] = 1300;
attribute[ATR_HITPOINTS] = 1300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_Fighter", 18, 2, PodroznikArmor);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_MAGE,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Long_04);
EquipItem		(self, ItRw_Bow_War_01);
CreateInvItems  (self,ItAt_Wolf_01,3);
CreateInvItems  (self,ItAt_Claws_01,2);
CreateInvItems  (self,ItFo_wineberrys_01,2);
CreateInvItems  (self,ItFoMuttonRaw,5);
CreateInvItems  (self,ItFobeer,2);
CreateInvItems  (self,Schutzring_Geschosse1,3);
CreateInvItems  (self,Schutzring_Magie1,1);
EquipItem	(self,FireMaster_Amulet);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3078;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3078()
{
TA_Stay (06,00,00,00,"PATH_TO_PLATEAU04");
TA_Smoke (00,00,04,00,"AV");
TA_Stand (04,00,06,00,"PATH_TO_PLATEAU04");
};
FUNC VOID Rtn_castle_3078 ()
{
TA_GuidePC (06,00,00,00,"LOCATION_19_03_PATH_RUIN7");
TA_GuidePC (00,00,04,00,"LOCATION_19_03_PATH_RUIN7");
TA_GuidePC (04,00,06,00,"LOCATION_19_03_PATH_RUIN7");
};
FUNC VOID Rtn_castle2_3078 ()
{
TA_Drained_YBerion (06,00,00,00,"LOCATION_19_03_PATH_RUIN7");
TA_Drained_YBerion (00,00,04,00,"LOCATION_19_03_PATH_RUIN7");
TA_Drained_YBerion (04,00,06,00,"LOCATION_19_03_PATH_RUIN7");
};