instance NON_2702_SZEFU (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Wilson";
Npctype = Npctype_Main;
guild = GIL_BAU;
level = 70;
voice = 8;
id = 2702;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 130;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",120, 0,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, Miecz2H5);
EquipItem		(self, ItRw_Bow_War_01);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,33);
CreateInvItems  (self,ItArScrollLight,2);
CreateInvItems  (self,ItArScrollFirestorm,2);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,500);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2702;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2702 ()
{
TA_SitAround (18,00,14,22,"HUNTERS_BENCH1");
TA_Boss 	 (14,22,18,00,"HUNTERS_ENTER_CAVE");
};
FUNC VOID Rtn_cavalorn_2702 ()
{
TA_Smalltalk (08,00,15,25,"OW_SAWHUT_SLEEP_01");
TA_Smoke (15,25,17,15,"OW_SAWHUT_SLEEP_01");
TA_Smalltalk (17,15,19,40,"OW_SAWHUT_SLEEP_01");
TA_PracticeSword (19,40,21,00,"OW_SAWHUT_MOLERAT_MOVEMENT8");
TA_Sleep (21,00,08,00,"OW_SAWHUT_SLEEP_01");
};
FUNC VOID Rtn_czekanie_2702 ()
{
TA_Stand (06,00,18,00,"LOWCA1");
TA_Stay (18,00,21,32,"LOWCA1");
TA_Smoke (21,32,06,00,"LOWCA1");
};
FUNC VOID Rtn_atak_2702 ()
{
TA_FollowPC (06,00,18,00,"LOWCA1");
TA_FollowPC (18,00,21,32,"LOWCA1");
TA_FollowPC (21,32,06,00,"LOWCA1");
};
FUNC VOID Rtn_wait_2702 ()
{
TA_Stand (06,00,18,00,"LOCATION_11_06");
TA_Stay (18,00,21,32,"LOCATION_11_06");
TA_Stand (21,32,06,00,"LOCATION_11_06");
};
FUNC VOID Rtn_mine_2702 ()
{
TA_SitAround (06,00,14,22,"OW_PATH_1_15");
TA_Stand (14,22,18,00,"OW_PATH_1_15");
TA_Stand (18,00,06,00,"OW_PATH_1_15");
};