instance NON_4061_Jeremy (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Jeremy";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 3;
voice = 3;
id = 4061;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 10;
attribute[ATR_DEXTERITY] = 10;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 45;
attribute[ATR_HITPOINTS] = 28;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 2,"Hum_Head_Bald",10, 2,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Club_01);
CreateInvItems  (self,ItAt_Meatbug_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_4061;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_4061 ()
{
TA_Walk (06,00,18,00,"CIPA");
TA_Walk (18,00,06,00,"CIPA");
};
FUNC VOID Rtn_life_4061 ()
{
TA_Stand (06,00,17,00,"ZLU1");
TA_Smoke (17,00,20,30,"ZLU1");
TA_SitAround (20,30,00,00,"ZUL2");
TA_Sleep (00,00,06,00,"DUP1");
};
