instance NON_3922_Wiezien (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Jarred";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 2;
voice = 11;
id = 3922;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 15;
attribute[ATR_DEXTERITY] = 15;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 30;
attribute[ATR_HITPOINTS] = 30;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",3, 2,"Hum_Head_Pony",12, 2,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_3922;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_3922 ()
{
TA_StandAround (00,00,12,00,"WIEZIEN3");
TA_StandAround (12,00,00,00,"WIEZIEN3");
};
FUNC VOID Rtn_anvil_3922 ()
{
TA_SitAround (00,00,12,00,"FLETCHER_SIT");
TA_SitAround (12,00,00,00,"FLETCHER_SIT");
};
