instance NON_2098_Stra¿nik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = name_Gardist;
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 30;
voice = 4;
id = 2098;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 80;
attribute[ATR_DEXTERITY] = 80;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Bald",2, 2,GRD_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_Light_01);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoCrawlersoup,2);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_2098;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2098 ()
{
TA_Smoke (06,00,18,00,"VM_GRD2");
TA_Smoke (18,00,06,00,"VM_GRD2");
};
