instance NON_2094_Glest (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Glest";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 10;
voice = 3;
flags		=	NPC_FLAG_IMMORTAL;
id = 2094;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 0,"Hum_Head_Bald",11, 0,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoCrawlersoup,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_2094;
//Generated by Gothic NPC Maker
};

//informacja: ta rutyna nie jest już wykorzystywana, npc nie pojawia się w Old_camp
FUNC VOID Rtn_prestart_2094 ()
{
TA_SitAround	 (05,00,10,45,"OCR_LAKE_4");
TA_WashSelf		 (10,45,11,20,"OCR_LAKE_4");
TA_Stand		 (11,20,17,35,"GLEST_WP1");
TA_SitAround	 (17,35,21,45,"OCR_LAKE_4");
TA_Smoke		 (21,45,00,35,"GLEST_WP1");
TA_Sleep	 	(00,00,05,00,"GLEST_WP2");
};

FUNC VOID Rtn_start_2094 ()
{
TA_SitCampfire (06,00,18,00,"GLEST_VM");
TA_SitCampfire (18,00,06,00,"GLEST_VM");
};
