instance NON_3070_Nidas (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Mroczny s³uga Nidas";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 70;
voice = 10;
id = 3070;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 80;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 600;
attribute[ATR_MANA] = 600;
attribute[ATR_HITPOINTS_MAX] = 700;
attribute[ATR_HITPOINTS] = 700;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 0,"Hum_Head_Bald", 15,  1, DMB_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_MAGE,6);

//----------Ekwipunek----------
CreateInvItems  (self,ItArRunePyrokinesis,1);
CreateInvItems  (self,ItArRuneCharm,1);
CreateInvItems  (self,ItArRuneIceCube,1);
CreateInvItems  (self,ItArRuneChainLightning,1);
CreateInvItems  (self,ItMijoint_3,10);
CreateInvItems  (self,ItMi_Stuff_Cup_02,2);
CreateInvItems  (self,ItMiNugget,300);
CreateInvItems  (self,ItFo_Potion_Mana_01,20);
CreateInvItems  (self,ItFo_Potion_Health_01,20);
CreateInvItems  (self,listasmierci,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Mage;
daily_routine = Rtn_start_3070;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3070 ()
{
TA_Smoke (06,00,18,00,"OW_PATH_ABYSS_4_5");
TA_Smoke (18,00,06,00,"OW_PATH_ABYSS_4_5");
};
