instance NON_3931_Dorian (Npc_Default)
{
//***POPRAWIONY***

//----------Info ogolne----------

name = "Dorian";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 5;
voice = 3;
id = 3931;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 15;
attribute[ATR_DEXTERITY] = 15;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 0,"Hum_Head_FatBald", 3,  3,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_3931;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3931 ()
{
TA_StandAround (00,00,12,00,"WIEZIEN_DAVOR");
TA_StandAround (12,00,00,00,"WIEZIEN_DAVOR");
};
func void rtn_free_3931 ()
{
TA_Boss (00,00,12,00,"OCC_MERCS_HALLWAY_BACK");
TA_Boss (12,00,00,00,"OCC_MERCS_HALLWAY_BACK");
};
