instance NON_2705_Rakus (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Rakus";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 50;
voice = 4;
id = 2705;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 129;
attribute[ATR_DEXTERITY] = 120;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",46, 1,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, Miecz2H5);
CreateInvItems  (self,ItAt_Waran_01,2);
CreateInvItems  (self,ItAt_Lurker_01,2);
CreateInvItems  (self,ItFo_wineberrys_01,3);
CreateInvItems  (self,ItMiNugget,356);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2705;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2705 ()
{
TA_WashSelf (06,00,06,20,"LOCATION_02_05");
TA_Boss (06,20,11,35,"HUNTERS_ENTER_CAVE");
TA_SitCampfire (11,35,14,50,"LOCATION_02_04");
TA_CookForMe 	(14,50,16,20,"LOCATION_02_08");
TA_Smith_Sharp 		(16,20,17,15,"OW_LOCATION_02_08");
TA_Skrzynka 		(17,15,20,40,"LOCATION_02_07");
TA_BOSS 		(20,40,22,55,"HUNTERS_VIEWPOINT");
TA_Sleep 		(22,55,06,00,"LOCATION_02_07");
};
FUNC VOID Rtn_cava_2705 ()
{
TA_Smalltalk (08,00,15,25,"OW_SAWHUT_SLEEP2");
TA_Stand (15,25,17,15,"OW_SAWHUT_SLEEP2");
TA_Smalltalk (17,15,19,40,"OW_SAWHUT_SLEEP2");
TA_Smoke (19,40,21,00,"OW_SAWHUT_SLEEP2");
TA_Sleep (21,00,08,00,"OW_SAWHUT_SLEEP2");
};
FUNC VOID Rtn_wait_2705 ()
{
TA_Smalltalk (06,00,08,33,"KEMP1");
TA_Smalltalk (08,33,06,00,"KEMP1");
};
FUNC VOID Rtn_atak_2705 ()
{
TA_Smalltalk (06,00,08,33,"LOWCA3");
TA_Stand (08,33,06,00,"LOWCA3");
};
FUNC VOID Rtn_burdel_2705 ()
{
TA_FollowPC (06,00,08,33,"LOWCA3");
TA_FollowPC (08,33,06,00,"LOWCA3");
};