instance NON_2099_Kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Kopacz";
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 5;
voice = 5;
id = 2099;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 130;
attribute[ATR_HITPOINTS] = 130;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 3,"Hum_Head_Bald",4, 3,VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoCrawlersoup,2);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_2099;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2099 ()
{
TA_Smoke (18,00,06,00,"ZL6");
TA_Smoke (06,00,18,00,"ZL6");
};
