instance NON_3921_Wiezien (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Karl";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 2;
voice = 3;
id = 3921;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 15;
attribute[ATR_DEXTERITY] = 15;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 30;
attribute[ATR_HITPOINTS] = 30;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",3, 0,"Hum_Head_Thief",0, 0,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_3921;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_3921 ()
{
TA_SitAround (00,00,12,00,"OCC_CELLAR_BACK_LEFT_CELL");//zamienieni
TA_SitAround (12,00,00,00,"OCC_CELLAR_BACK_LEFT_CELL");
};
func void rtn_newcamp_3921 ()
{
TA_StandAround (00,00,12,00,"NC_SMALL_CAVE_STAIRS");
TA_StandAround (12,00,00,00,"NC_SMALL_CAVE_STAIRS");
};
