instance NOV_5066_Poszukiwacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Poszukiwacz";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 40;
voice = 3;
id = 5066;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 120;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 350;
attribute[ATR_HITPOINTS] = 350;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Psionic",64, 1,STT_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Staff_01);
CreateInvItems  (self,ItArScrollFirebolt,10);
CreateInvItems  (self,ItArScrollfirerain,10);
CreateInvItems  (self,ItArScrollIceCube,10);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5066;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5066 ()
{
TA_Stay (06,00,18,00,"TPL_382");
TA_Stay (18,00,06,00,"TPL_382");
};
