instance NOV_5006_Steh (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Steh";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 35;
voice = 3;
id = 5006;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 322;
attribute[ATR_HITPOINTS] = 322;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Psionic",18, 0,NOV_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);
Npc_SetTalentSkill (self, NPC_TALENT_MAGE,3);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Short_05);
EquipItem		(self, ItRw_Bow_Long_01);
CreateInvItems  (self,ItFoApple,1);
CreateInvItems  (self,ItFoMuttonRaw,1);
CreateInvItems  (self,ItArRuneFirebolt,1);
CreateInvItems  (self,ItFo_Potion_Mana_01,1);
CreateInvItems  (self,ItFo_Potion_Mana_02,1);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
CreateInvItems  (self,Schutzring_Feuer1,1);
CreateInvItems  (self,Schutzring_Geschosse1,1);
CreateInvItems  (self,Schutzring_Magie1,1);
CreateInvItems  (self,ItArRuneFireball,1);
CreateInvItems  (self,ItArRuneThunderBolt,1);
CreateInvItems  (self,ItFoApple,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Mage;
daily_routine = Rtn_start_5006;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5006 ()
{
TA_SitAround (19,15,11,45,"PSI_BENH_STEH");
TA_Stand (11,45,12,37,"BIJACZ2_HANDLARZ");
TA_Smoke (12,37,13,00,"BIJACZ2_HANDLARZ");
TA_SitAround (13,00,15,35,"BIJACZ2_HANDLARZ");
TA_PickRice (15,35,18,22,"BIJACZ2_HANDLARZ");
TA_SitAround (18,22,19,15,"BIJACZ2_HANDLARZ"); //to potem można zmienić na rutynę czytania
};
func void rtn_tot_5006 ()
{
	ta_stay (06,00,11,45,"winnejgrze");
	ta_stay (11,45,06,00,"kibelekwciechocinku");	
};