instance NOV_5068_Poszukiwacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Poszukiwacz";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 35;
voice = 6;
id = 5068;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 80;
attribute[ATR_DEXTERITY] = 80;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 250;
attribute[ATR_HITPOINTS] = 250;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1 ,"Hum_Head_Psionic", 20,  1, PoszukiwaczArmor);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Staff_03);
CreateInvItems  (self,ItFo_Plants_mountainmoos_01,3);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5068;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5068 ()
{
TA_PracticeMagic (22,00,06,00,"POGAN2");
TA_PracticeMagic (06,00,22,00,"POGAN2");
};
