instance NON_7501_Opetany_Kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Podejrzany Kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 6;
voice = 6;
id = 7501;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 35;
attribute[ATR_DEXTERITY] = 35;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 80;
attribute[ATR_HITPOINTS] = 80;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Bald",116, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoMeatbugragout,1);
CreateInvItems  (self,ItFo_Plants_mushroom_01,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7501;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7501 ()
{
TA_stand (00,00,12,00,"JOSEP2");
TA_stand (12,00,00,00,"JOSEP2");
};

instance NON_7502_Opetany_Kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Podejrzany Kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 6;
voice = 6;
id = 7502;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 35;
attribute[ATR_DEXTERITY] = 35;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 80;
attribute[ATR_HITPOINTS] = 80;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
	Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_Bald", 37, 2, VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoMeatbugragout,1);
CreateInvItems  (self,StoneOfKnowledge,1);
CreateInvItems  (self,ItFo_Plants_mushroom_01,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7502;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7502 ()
{
TA_stand (00,00,12,00,"KOPACZ_ZBIR1");
TA_stand (12,00,00,00,"KOPACZ_ZBIR1");
};

instance NON_7503_Opetany_Kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Podejrzany Kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 6;
voice = 6;
id = 7503;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 35;
attribute[ATR_DEXTERITY] = 35;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 80;
attribute[ATR_HITPOINTS] = 80;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Bald",8, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoMeatbugragout,1);
CreateInvItems  (self,ItFo_Plants_mushroom_01,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7503;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7503 ()
{
TA_stand (00,00,12,00,"KOPACZ_ZBIR2");
TA_stand (12,00,00,00,"KOPACZ_ZBIR2");
};

instance NON_7504_Opetany_Kopacz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Podejrzany Kopacz";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 6;
voice = 6;
id = 7504;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 35;
attribute[ATR_DEXTERITY] = 35;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 80;
attribute[ATR_HITPOINTS] = 80;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",16, 1,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Old_01);
CreateInvItems  (self,ItFo_Potion_Water_01,1);
CreateInvItems  (self,ItFoMeatbugragout,1);
CreateInvItems  (self,ItFo_Plants_mushroom_01,2);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_7504;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_7504 ()
{
TA_stand (00,00,12,00,"KOPACZ_ZBIR3");
TA_stand (12,00,00,00,"KOPACZ_ZBIR3");
};