instance ORG_2045_Ghoram (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Ghoram";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 323;
voice = 1;
id = 2045;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 350;
attribute[ATR_HITPOINTS] = 350;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_CookSmith",0, 1,"Hum_Head_Bald",50, 1,ORG_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Short_04);
CreateInvItems  (self,ItAt_Meatbug_01,2);
CreateInvItems  (self,ItFoApple,10);
CreateInvItems  (self,ItFo_wineberrys_01,10);
CreateInvItems  (self,ItFoMutton,10);
CreateInvItems  (self,ItFocheese,10);
CreateInvItems  (self,ItFoBooze,10);
CreateInvItems  (self,ItFoBeer,10);
CreateInvItems  (self,ItFoWine,20);
CreateInvItems  (self,ItFo_Potion_Health_01,5);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_2045;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2045 ()
{
TA_Stand (06,00,13,00,"KARCZMARZ2");
TA_Smoke (13,00,15,22,"KARCZMARZ2");
TA_Stand (15,22,17,34,"KARCZMARZ2");
TA_Cook (17,34,21,00,"KARCZMARZ3");
TA_Stand (21,00,06,00,"KARCZMARZ3");
};
