instance GRD_2650_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2650;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",7, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,2);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Health_01,5);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2650;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2650 ()
{
TA_stand (0,00,12,00,"OW_PATH_1_5_12_1");
TA_STAND (12,00,0,00,"OW_PATH_1_5_12_1");
};
instance GRD_2651_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2651;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 13,  1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2651;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2651 ()
{
TA_STAND (0,00,12,00,"OW_PATH_1_5_12_2");
TA_STAND (12,00,0,00,"OW_PATH_1_5_12_2");
};
instance GRD_2652_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2652;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 13,  1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2652;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2652 ()
{
TA_STAND (0,00,12,00,"OW_PATH_1_5_1");
TA_STAND (12,00,0,00,"OW_PATH_1_5_1");
};
instance GRD_2653_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2653;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 13,  1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2653;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2653 ()
{
TA_STAND (0,00,12,00,"OW_PATH_1_5_9");
TA_STAND (12,00,0,00,"OW_PATH_1_5_9");
};
instance GRD_2654_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2654;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Bald",10, 2,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,2);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2654;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2654 ()
{
TA_STAND (0,00,12,00,"OW_PATH_1_5_6");
TA_STAND (12,00,0,00,"OW_PATH_1_5_6");
};
//ci atakują Thorusa i spółkę
instance GRD_2655_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2655;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Bald",10, 2,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,2);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2655;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2655 ()
{
TA_STAND (0,00,12,00,"RAVEN_NK");
TA_STAND (12,00,0,00,"RAVEN_NK");
};
instance GRD_2656_Gardist (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_Guard;
guild = GIL_GRD;
level = 20;
voice = 15;
id = 2656;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Bald",10, 2,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_LightGuardsSword_03);
EquipItem		(self, ItRw_Crossbow_02);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFocheese,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItFoBeer,2);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItLsTorch,2);
CreateInvItems  (self,ItMiNugget,15);
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MAster;
daily_routine = Rtn_start_2656;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2656 ()
{
TA_STAND (0,00,12,00,"OW_PATH_1_12");
TA_STAND (12,00,0,00,"OW_PATH_1_12");
};