instance STT_2046_Flint (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Flint";
Npctype = Npctype_Main;
guild = GIL_STT;
level = 5;
voice = 7;
id = 2046;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 40;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 160;
attribute[ATR_HITPOINTS] = 160;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",1, 0,STT_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Short_03);
CreateInvItems  (self,ItFoLoaf,2);
CreateInvItems  (self,ItForice,1);
CreateInvItems  (self,ItFoWine,1);
CreateInvItems  (self,ItMiNugget,35);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_prestart_2046;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_prestart_2046 ()
{
TA_Smoke (07,35,12,25,"OCR_ARENA_BED_PIPE");
TA_SitAround (12,25,22,00,"OCR_FLINT_BENCH");
TA_Sleep (22,00,07,35,"OCR_ARENA_BED_PIPE");
};
FUNC VOID Rtn_start_2046 ()
{
TA_Stay (06,00,22,00,"ZBOJ");
TA_Stay (22,00,06,00,"ZBOJ");
};
FUNC VOID Rtn_follow_2046 ()
{
TA_FollowPC (06,00,22,00,"ZBOJ");
TA_FollowPC (22,00,06,00,"ZBOJ");
};
FUNC VOID Rtn_camp_2046 ()
{
TA_Stand (06,00,22,00,"CAMP_FLINT"); //do zmiany  //edit 1.25 poprawione (1.4) kwiecień 2013
TA_Smoke (22,00,06,00,"CAMP_FLINT");
};
FUNC VOID Rtn_arena_2046 ()
{
	TA_GuidePC (08,00,20,00,"OCR_ARENABATTLE_TRAIN");
	TA_GuidePC (20,00,08,00,"OCR_ARENABATTLE_TRAIN");
};
