
//******************************************************
//******* MYŒLIWI
//******** SKRYPTY NPC
// === od wersji 1.24 - full
//******************************************************

instance NON_5600_Alex (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Alex";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 60;
voice = 11;
flags =	NPC_FLAG_IMMORTAL; //nieœmiertelny handlarz
id = 5600;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 130;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex4,teethtex,ruestung	
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 0 ,"Hum_Head_Bald", 100,  2, HUN_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, Miecz1H2);
EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFoMutton,12);
CreateInvItems  (self,ItMiNugget,255);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5600;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5600 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_WashSelf (06,00,09,33,"WIADRO");
TA_SitAround (09,33,15,21,"HUT_HUNTERS_BENCH");
TA_PickRice (15,21,18,00,"ALEX_CAMP");
TA_Smoke (18,00,20,34,"SPAWN_TALL_PATH_BANDITOS2_02");
TA_SitAround (20,34,06,00,"HUT_HUNTERS_BENCH");
};
FUNC VOID Rtn_lochy_5600 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_Stand (06,00,18,00,"ALEX_CELL");
TA_Stay (18,00,06,00,"ALEX_CELL");
};

FUNC VOID Rtn_troll_5600 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_GuidePC (06,00,18,00,"OW_PATH_152K");
TA_GuidePC (18,00,06,00,"OW_PATH_152K");
};




instance NON_5601_Firn (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Firn";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 28;
voice = 11;
id = 5601;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 90;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0 , 0,"Hum_Head_Bald", 3, 1,HUN_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------

EquipItem		(self, Helmet1);
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,14);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItMiNugget,124);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5601;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5601 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_Boss (06,00,09,33,"PACZ2");
TA_Stand (09,33,15,21,"PACZ2");
TA_Boss (15,21,06,00,"PACZ2");
};
FUNC VOID Rtn_after_start_5601 ()
{
TA_Boss (06,00,09,33,"SPAWN_TALL_PATH_BANDITOS2_02");
TA_Stand (09,33,15,21,"SPAWN_TALL_PATH_BANDITOS2_02");
TA_Boss (15,21,06,00,"SPAWN_TALL_PATH_BANDITOS2_02");
};


instance NON_5603_Claw (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Claw";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 25;
voice = 11;
id = 5603;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 55;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;
//----------Wyglad----------
Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Thief",72,2,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);
//----------Umiejetnasci----------
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);
//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_03);
EquipItem		(self, ItRw_Bow_Long_05);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,55);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,6);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5603;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5603 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_PotionAlchemy (06,00,09,33,"CLAW");
TA_PotionAlchemy (09,33,15,10,"CLAW");
TA_SitCampfire (15,10,06,00,"CLAW_CAMP");
};
FUNC VOID Rtn_chory_5603 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_Sleep (06,00,09,33,"BED_MYS");
TA_Sleep (09,33,15,10,"BED_MYS");
TA_Sleep (15,10,06,00,"BED_MYS");
};
func void Rtn_follow_5603 ()
{
TA_FOLLOWPC(06,00,18,00,"CLAW");
TA_FOLLOWPC(18,00,06,00,"CLAW");
};
instance NON_5632_Duch (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Biorn";
Npctype = Npctype_Friend;
guild = GIL_NONE;
level = 15;
voice = 11;
id = 5632;
//flags		=	NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

	protection	[PROT_BLUNT]		=	999;
	protection	[PROT_EDGE]			=	999;
	protection	[PROT_POINT]		=	399;
	protection	[PROT_FIRE]			=	0;
	protection	[PROT_FLY]			=	999;
	protection	[PROT_MAGIC]		=	999;
//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds (self,"Humans_drunken.mds");
Mdl_SetVisualBody 		(self,"Zom_Body",1,1,"Zom_Head",1,2,-1);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_03);
//EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,33);
CreateInvItems  (self,ItArScrollLight,2);
CreateInvItems  (self,ItArScrollFirestorm,2);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,200);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5632;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5632 ()
{
TA_Stay (00,00,03,33,"DUCH1");
TA_Stay (03,33,15,10,"DUCH2");
TA_Stay (15,10,00,00,"DUCH2");
};

FUNC VOID Rtn_die_5632 ()
{
TA_Die (00,00,18,00,"UTRIEL_SLEEP");
TA_Die (18,00,00,00,"UTRIEL_SLEEP");
};

instance NON_5633_Duch (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Biorn";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 60;
voice = 11;
id = 5633;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 450;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody 		(self,	"Zom_Body",		1,			0,			"Zom_Head", 1,  		2,			-1);
//Mdl_SetVisualBody (self,"hum_body_naked0",8, 1,"Hum_Head_Bald",75, 1,NON_LEATHER_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
//EquipItem		(self, ItMw_2H_Sword_02);
//EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,100);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5633;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5633 ()
{
TA_Stay (00,00,03,33,"DUCH1");
TA_Stay (03,33,15,10,"DUCH2");
TA_Stay (15,10,00,00,"DUCH2");
};


instance NON_5677_Stary (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Tom";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 23;
voice = 12;
id = 5677;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",3,0,"Hum_Head_Bald",0,0,NON_SWAMPSHARK_ARMOR);//fixed siwa
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------

//EquipItem		(self, Helmet1);
EquipItem		(self, ItMw_1H_Sword_03);
EquipItem		(self, ItRw_Bow_Long_05);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItMiNugget,145);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5677;
};
FUNC VOID Rtn_start_5677 ()
{
TA_Stand (06,00,08,33,"MYSLIWY_3");
TA_Stand (08,33,12,21,"MYSLIWY3");
TA_HerbAlchemy (12,21,16,00,"MYSLIWY_2");
TA_Sleep (16,00,18,00,"MYSLIWY_1");
TA_HerbAlchemy (18,00,20,00,"MYSLIWY_2");
TA_Smoke (20,00,23,00,"MYSLIWY_3");
TA_Sleep (23,00,06,00,"MYSLIWY_1");
};

FUNC VOID Rtn_nockruka_5677 ()
{
TA_Smalltalk (06,00,08,33,"TOM_NK");
TA_Smalltalk (08,33,06,00,"TOM_NK");
};
instance NON_5611_Jonas (Npc_Default)
{
//----------Info ogolne----------

name = "Jonas";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 20;
voice = 8;
id = 5611;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 36;
attribute[ATR_DEXTERITY] = 45;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 280;
attribute[ATR_HITPOINTS] = 280;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Bald",102, 1,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_1H,7);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_02);
EquipItem		(self, ItRw_Bow_Long_06);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItMI_saw,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,130);
//------------------ handle
CreateInvItems  (self,ItFo_Plants_Bloodwood_01,10);
CreateInvItems  (self,ItFo_Plants_Towerwood_01,10);
CreateInvItems  (self,ItFo_Plants_Trollberrys_01,1);
CreateInvItems  (self,ItMi_Wood_01,10);
CreateInvItems  (self,ItMi_Wood_02,10);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5611;
};
FUNC VOID Rtn_start_5611 () //edycja
{
TA_WorkMOB (06,00,11,20,"DRWAL_MS1");
TA_RepairHut(11,20,12,30,"REPAIR_MS1");
TA_Stand (12,30,13,40,"FOOD_MS1");
TA_WorkMOB (13,40,18,00,"DRWAL_MS1");
TA_SitCampfire (18,00,06,00,"TALK2_MS1");
};
FUNC VOID Rtn_start2_5611 () //edycja
{
TA_SitAround (06,00,11,20,"OLIVIER_BENCH");
TA_RepairHut(11,20,12,30,"REPAIR_MS1");
TA_Stand (12,30,13,40,"FOOD_MS1");
TA_WorkMOB (13,40,18,00,"DRWAL_MS1");
TA_SitCampfire (18,00,06,00,"TALK2_MS1");
};
instance NON_5605_Hunter (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Mysliwy2;
Npctype = Npctype_MAIN;
guild = GIL_NONE;
level = 13;
voice = 8;
id = 5605;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 45;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 140;
attribute[ATR_HITPOINTS] = 140;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Psionic",58, 1,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_02);
EquipItem		(self, ItRw_Bow_Long_02);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItMI_saw,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItMiNugget,47);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5605;
};
FUNC VOID Rtn_start_5605 ()
{
TA_SitCampfire (06,00,12,30,"CAMP_MS1");
TA_REPAIRHUT (12,30,16,40,"REPAIR_MS1");
TA_PickRice (16,40,18,00,"CAMP_MS1");
TA_REPAIRHUT (18,00,20,34,"REPAIR_MS1");
TA_SitCampfire (20,34,06,00,"CAMP_MS1");
};
instance NON_5606_Hunter (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Mysliwy3;
Npctype = Npctype_Ambient;
guild = GIL_NONE;
level = 13;
voice = 8;
id = 5606;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 45;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 140;
attribute[ATR_HITPOINTS] = 140;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_Pony", 53,  1,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_01);
EquipItem		(self, ItRw_Bow_Long_03);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItMI_saw,2);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItMiNugget,47);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5606;
};
FUNC VOID Rtn_start_5606 ()
{
TA_SmallTALK (06,00,13,00,"TALK2_MS1");
TA_SitCampfire (13,00,15,00,"TALK2_MS1");
TA_PickRice (15,00,18,00,"REPAIR_MS1");
TA_WOrkMOB (18,00,21,00,"DRWAL_MS1");
TA_SmallTALK (21,00,23,00,"TALK2_MS1");
TA_SitCampfire (21,00,23,00,"TALK2_MS1");
};
FUNC VOID Rtn_wypad_5606 ()
{
TA_RepairHut	 (06,00,12,00,"OW_SAWHUT_MOLERAT_MOVEMENT2"); //dopisane!!
TA_PracticeSword (12,00,16,00,"OW_SAWHUT_MOLERAT_MOVEMENT4");
TA_Smoke		 (16,00,18,00,"OW_SAWHUT_MOLERAT_MOVEMENT8");
TA_RepairHut	 (18,00,20,00,"OW_SAWHUT_MOLERAT_MOVEMENT2");
TA_Stand		 (20,00,06,00,"OW_SAWHUT_SLEEP_01"); 
};
instance NON_5610_Hunter (Npc_Default)
{
//----------Info ogolne----------

name = NAME_Mysliwy1;
Npctype = Npctype_Ambient;
guild = GIL_NONE;
level = 10;
voice = 8;
id = 5610;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 45;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 140;
attribute[ATR_HITPOINTS] = 140;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 3,"Hum_Head_Bald",4, 3,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_01);
EquipItem		(self, ItRw_Bow_Long_01);
CreateInvItems  (self,ItAt_Teeth_01,1);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,ItMiNugget,30);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5610;
};
FUNC VOID Rtn_start_5610 ()
{
TA_SmallTALK (06,00,13,00,"TALK1_MS1");
TA_Cook (13,00,17,22,"COOK_MS1");
TA_Stand (17,22,18,00,"COOK_MS1");
TA_Cook (18,00,21,00,"COOK_MS1");
TA_SmallTALK (21,00,23,00,"TALK1_MS1");
TA_Stand (23,00,06,00,"TALK1_MS1");
};


instance NON_5613_Olivier (Npc_Default)
{
//----------Info ogolne----------

name = "Olivier";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 15;
voice = 8;
id = 5613;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 45;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_FatBald", 17,  4, NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_BOW,1);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_01);//ostrze
EquipItem		(self, ItRw_Bow_Long_01);
CreateInvItems  (self,ItMiNugget,40);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5613;
};
FUNC VOID Rtn_start_5613 ()
{
TA_BoSS (06,00,16,00,"WYKOPALISKA1_MS1");
TA_skrzynka (16,00,18,00,"CHEST2_MS1");
TA_Stand (18,00,20,00,"WYKOPALISKA1_MS1");
TA_UseHorn (20,00,01,00,"ROG1_MS1");
TA_UseHorn (01,00,06,00,"ROG2_MS1");
};
FUNC VOID Rtn_work_5613 ()
{
TA_WorkMOB (06,00,13,40,"DRWAL_MS1");
TA_skrzynka (13,40,14,00,"CHEST2_MS1");
TA_Stand (14,00,18,00,"WYKOPALISKA1_MS1");
TA_WorkMOB (18,00,20,00,"DRWAL_MS1");
TA_SitAround (20,00,06,00,"OLIVIER_BENCH");
};
FUNC VOID Rtn_guide1_5613 ()
{
TA_GuidePC (06,00,16,00,"OW_PATH_OC_NC6");
TA_GuidePC (16,00,06,00,"OW_PATH_OC_NC6");
};
FUNC VOID Rtn_guide2_5613 ()
{
TA_GuidePC (06,00,16,00,"HELPPOINT10");
TA_GuidePC (16,00,06,00,"HELPPOINT10");
};

instance NON_5614_Josep (Npc_Default)
{
	//-------- primary data --------
	
	name 		=	"Josep";
	npctype		=	npctype_main;
	guild 		=	GIL_NONE;      
	level 		=	5;
	voice 		=	9;
	id 			=	5614;

	//-------- abilities --------
	attribute[ATR_STRENGTH] 	= 60;
	attribute[ATR_DEXTERITY]	= 80;
	attribute[ATR_MANA_MAX] 	= 0;
	attribute[ATR_MANA] 		= 0;
	attribute[ATR_HITPOINTS_MAX]= 250;
	attribute[ATR_HITPOINTS] 	= 250;

	//-------- visuals --------
	// 				animations
	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
	//			body mesh     ,bdytex,skin,head mesh     ,headtex,teethtex,ruestung	
	Mdl_SetVisualBody (self,"hum_body_Naked0",3,2,"Hum_Head_Fighter", 0,  1, HUN_ARMOR_L);
	
	B_Scale (self);
	Mdl_SetModelFatness(self,0);
	
	fight_tactic	=	FAI_HUMAN_MASTER; 
	                            	
	//-------- Talente -------- 	                                  
	
	//-------- inventory --------                                    

		
	EquipItem (self, ItMw_1H_Scythe_01);
	CreateInvItems (self, ItFoRice,5);
	EquipItem (self, JosepSamulet);
	

	//-------------Daily Routine-------------
	daily_routine = Rtn_start_5614;
};

FUNC VOID Rtn_start_5614 ()
{
	TA_Sleep		(20,35,07,35,"NC_PATH_PEASANT4");
	TA_PickRice		(07,35,20,35,"NC_PATH81");
};
FUNC VOID Rtn_camp_5614 ()
{
	TA_smoke		(20,35,07,35,"WYKOAPLISKA2_MS1");
	TA_smoke		(07,35,20,35,"SPAWN_OW_BLOODFLY_12");
};

FUNC VOID Rtn_beliar_5614 ()
{
	TA_smoke		(20,35,07,35,"JOSEP2");
	TA_smoke		(07,35,20,35,"JOSEP2");
};


FUNC VOID Rtn_camp2_5614 ()
{
	TA_Stand		(20,35,07,00,"SPAWN_OW_BLOODFLY_12");
	TA_CookForMe	(07,00,07,35,"CAMP_SHRAT");
	TA_PickRice		(07,35,20,35,"WYKOAPLISKA2_MS1");
};






