instance TPL_5004_Shawn (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Shawn";
Npctype = Npctype_Main;
guild = GIL_TPL;
level = 40;
voice = 2;
id = 5004;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Mage.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Psionic",15, 0,TPL_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_MAGE,4);
Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Staff_02);
CreateInvItems  (self,ItArRuneLight,1);
CreateInvItems  (self,ItArRuneFireball,1);
CreateInvItems  (self,ItArRuneThunderBolt,1);
CreateInvItems  (self,ItFo_Potion_Mana_02,1);
CreateInvItems  (self,ItFo_Potion_Health_01,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Mage;
daily_routine = Rtn_start_5004;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5004 ()
{
TA_Smoke (06,00,16,00,"ADMIN");
TA_WalkAround (16,00,06,00,"ADMIN2");
};
