instance TPL_5083_OldAlchemyMan (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stary alchemik";
Npctype	= NPCTYPE_FRIEND;
guild = GIL_NONE;
level = 45;
voice = 4;
id = 5083;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 70;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 70;
attribute[ATR_MANA] = 70;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 15;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",5, 1,GUR_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_2H,2);

//----------Ekwipunek----------
EquipItem		(self, Miecz2H2); //1.3
CreateInvItems  (self,ItFoLoaf,1);
CreateInvItems  (self,ItFocheese,1);
CreateInvItems  (self,ItMiFlask,15);
CreateInvItems  (self,ItMi_Plants_Swampherb_01,2);
CreateInvItems  (self,ItMi_Alchemy_Sulphur_01,15);
CreateInvItems  (self,ItMi_Alchemy_Quicksilver_01,4);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,12);
CreateInvItems  (self,ItMi_Alchemy_Syrianoil_01,10);
CreateInvItems  (self,ItMi_Alchemy_Moleratlubric_01,15);
CreateInvItems  (self,ItMi_Alchemy_Alcohol_01,8);
CreateInvItems  (self,ItWr_FullRegeneratePotions,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5083;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5083 ()
{
TA_SitCampfire (06,00,18,00,"ALCHEMIK223");
TA_SitCampfire (18,00,06,00,"ALCHEMIK223");
};
FUNC VOID Rtn_die_5083 ()
{
TA_Die (06,00,18,00,"ALCHEMIK223");
TA_Die (18,00,06,00,"ALCHEMIK223");
};