instance VLK_5089_Tragaz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Tragarz";
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 5;
voice = 1;
id = 5089;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 60;
attribute[ATR_HITPOINTS] = 60;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 3,"Hum_Head_Bald",10, 3,VLK_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_5089;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5089 ()
{
TA_Stand (06,00,22,00,"ES2");
TA_Stand (22,00,06,00,"ES2");
};
FUNC VOID Rtn_las_5089 ()
{
TA_Stay (22,00,06,00,"PACHOL2");
TA_Stay (06,00,22,00,"PACHOL2");
};
FUNC VOID Rtn_follow_5089 ()
{
TA_FollowPC (06,00,22,00,"OC1");
TA_FollowPC (22,00,06,00,"OC1");
};
FUNC VOID Rtn_camp_5089 ()
{
TA_SitCampfire (06,00,22,00,"DOSTAWA2");
TA_SitCampfire (22,00,06,00,"DOSTAWA2");
};