instance VLK_3901_Robotnik (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn
//----------Info ogolne----------

name = "Robotnik";
Npctype = Npctype_Main;
guild = GIL_VLK;
level = 5;
voice = 3;
id = 3901;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 20;
attribute[ATR_DEXTERITY] = 20;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 50;
attribute[ATR_HITPOINTS] = 50;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",16, 0,VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Poker_01);
CreateInvItems  (self,ItMiNugget,5);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_3901;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_3901 ()
{
TA_RepairHut (5,00,20,00,"OCCWORKER");
TA_Stand (20,00,23,00,"OCR_HUT_44");
TA_Sleep (23,00,5,00,"OCR_HUT_44");
};
