instance VLK_2010_Poslaniec (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Pos³aniec";
Npctype = Npctype_Main;
guild = GIL_VLK;
level = 5;
voice = 2;
id = 2010;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 10;
attribute[ATR_DEXTERITY] = 10;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 45;
attribute[ATR_HITPOINTS] = 45;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 1,"Hum_Head_Thief",113, 1,VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Poker_01);
CreateInvItems  (self,ItMiNugget,1);
CreateInvItems  (self,ItFoLoaf,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_2010;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2010 ()
{
TA_Stay (06,00,12,00,"POSLANIEC");
TA_Stay (12,00,06,00,"POSLANIEC");
};
FUNC VOID Rtn_back_2010 ()
{
TA_Stay (06,00,12,00,"GOBBO_MASTERCAVE9");
TA_Stay (12,00,06,00,"GOBBO_MASTERCAVE9");
};
